### ISSUE TITLE
Bug - Sev 3 - Analytics bug: Account for duplicate firing of events

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6528] opened 2023-08-17 13:05 UTC
While completing the analytics review of the Letters & Documents feature (#6517 #5912), I discovered that vama_prof_update_address is sometimes firing more than once in the same timestamp for the same user, which means something is off in the logic as it should only fire once when the API call successfully puts the updated address information. Some of these cases logged up to 15 vama_prof_update_address at the same timestamp. It appeared to affect around 1% of users making address updates in June & July 2023 and 1% of sessions where it was logged at all.

I then considered **if this was happening with other events** and so I calculated for each event and each user how many times the event was logged with the same timestamp. Then, I grouped by event the total number of users whose count of timestamps was equal to their unique timestamps (meaning they never double logged that event) and those where the latter was larger than the former (meaning they double logged that event at least once).  Then the percent of users experiencing a double log of a particular event was calculated for each month August 2022 - July 2023. 

I found that almost all events that have been around for at least a couple months will have some duplicate firing. It appears this may [be a known issue with how GA logs ](https://stackoverflow.com/questions/57393777/firebase-bigquery-duplicate-events) things based on servers/user connection, etc. 

[Sheet with data analyzed
](https://docs.google.com/spreadsheets/d/1o0I8gVyTV3bLTV1EljSQVCk5Gdx7Nf02-m5-3TTl4q4/edit#gid=1358619808)

**To be investigated:**

- [ ] What is the expected level of duplicate logging? 
- [ ] Which custom events are exceeding this and is there a problem with their logic?
- [ ] Filtering/ETL solution to remove dupes

**Comment by alexandec** [comment] 2023-08-17 19:12
If the duplicates are due to us sending the same event multiple times, a couple solutions come to mind:
- If the dupes are caused by components re-rendering, we could address that within the individual components
- Alternatively we could debounce events globally. That is, if logAnalyticsEvent is called multiple times within a small interval (say, 1 second), we only send the event once

**Comment by g-opzt** [comment] 2023-09-05 17:00
With completion of #6615 the duplicate firings with the exact same timestamp have been filtered out. I do think there is still need to investigate close proximity firing of the same event so leaving this open for additional investigation.

**Comment by bischoffa** [comment] 2024-05-08 13:34
@OVezeamama I saw this old analytics bug issue from Greta. I assigned to you in case this is something you want to review and keep. If not feel free to close.

**Closed** 2024-09-02 21:43 UTC
Labels: sev-3, bug, analytics, scrubbed, global
