### ISSUE TITLE
Move API calls to home screen in order to collect analytics

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7300] opened 2023-11-16 01:23 UTC
Background:
- This ticket covers moving API calls, for features that will have home screen modules, to the home screen in order to capture analytics. 

AC:
For the following features, surface the API request to the home screen, log their respective analytics count, and retire the previous API call appropriately:
- Appointments
- Prescriptions
- Secure Messages
- Claims & Appeals

For example, if there are 3 unread secure messages, surface the API call for unread secure messages and log the number 3

Notes & References:
- [Home screen feature counting logic](https://docs.google.com/document/d/1D4TJk3l_lM0IrPqfU-6SgES3ohGdboOxo7SgMLyqIlU/edit)

**Comment by timwright12** [comment] 2023-12-11 16:00
@ajsarkar28 if this ticket isn't complete can we remove it from the "Pending Handoff" column?

**Comment by TKDickson** [comment] 2023-12-18 18:15
For grooming -- I don't think we can actually retire either appointments or secure messages, because of PN deep linking. Need to chat about this.

**Comment by TKDickson** [comment] 2023-12-18 18:16
QA Estimate: 2 points, since it's only partially testable (that the API calls have moved, and PN for messages in Android)

Portions of this that are untestable: analytics, appointments-related PN, and PN for messages in iOS.

**Comment by TKDickson** [comment] 2024-01-30 16:17
@dumathane plans on doing: 
- the analytics call testing (confirming that we're registering events at the points in the app where you'd expect it, and
- looking into if there are any race conditions under which analytics will not be sent

I will be testing to investigate if adding analytics/moving API calls (invisibly to veterans) slows down, or otherwise negatively impacts, veteran-facing app functionality. (Examples of bugs that could be introduced by these changes: #7779 and #7746)

In terms of testing coverage, I want to be looking into:
- Load times & erroring on home screen
- Load times & erroring on category screens
- Load times & erroring on feature lists, pagination, and feature details for impacted features (messages, Rx, claims and appeals, appointments)
- PN for messages

**Comment by TKDickson** [comment] 2024-02-12 20:03
* Mimicking a handle-able error (map local to a 408 response) for each of the 4 APIs worked as expected - failure was invisible on the home screen and didn't slow down further navigation; APIs were called again and showed error responses on the feature landing pages.
* Mocking verrrrry slow load times (by adding a breakpoint and then not sending the response for several seconds) for all of the 4 APIs also worked as expected. If I proceeded to the feature landing pages before the HS calls were resolved, the APIs fired again & no information showed until the responses were allowed through. Navigation through all of this loading was still allowed.

Still need to test PN for messages, as well as users with correct/valid info (making sure pagination works with the latest build) Will also need to test feature flag stuff when that's added.

**Comment by TKDickson** [comment] 2024-02-13 17:57
PN for messages has been down for at least a few days, likely not be able to test & still release today.

With the feature flag enabled `homeScreenPrefetch`, the app behaves the same as today's current develop build (in terms of when the APIs are called -- aka they are not called on homescreen, but are called on feature lists & appear to be functioning appropriately there). The only feature that I can't test appropriate function on the feature & beyond with is Rx, because sometime overnight our only staging user with Rx data has broken.

**Comment by TKDickson** [comment] 2024-02-14 15:03
Confirmed this morning that:
* Rx and messaging work as expected with the feature flag off
* With the feature flag on, PN for messages work fine (if not logged in, you log in & are brought to message details while the APIs run in the background. If logged in, brought to message details without APIs running)
* With feature flag on, PN for messages also work fine (and don't start the homescreen APIs)

**Comment by TKDickson** [comment] 2024-02-14 19:56
Found #7990 while testing this in develop; is not release blocking. Closing.

**Closed by TKDickson** 2024-02-14 19:56 UTC
Labels: QA, front-end, analytics, global, QA 5

**Comment by TKDickson** [comment] 2024-02-27 19:56
Events created: vama_hs_appts_count, vama_hs_claims_count, vama_hs_rx_count, vama_hs_sm_count, and vama_hs_load_time
