### ISSUE TITLE
Waygate (availability framework) Implementation: Health, and Payments

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#7233] opened 2023-11-08 17:20 UTC
## Description 
Waygates need to be placed and confirmed toggle-able in three different use cases across all applicable pages within the app. 

As part of this story we want to:   

- Ensure all relevant pages are able to be intercepted by a waygate setup and display as we would want them to.

## Acceptance Criteria
  

The following three AC's need to be applied to the attached list of screens:

-  [x] Confirm Use Case 1 appropriately intercepts page navigation to the given page.
-  [x] Confirm Use Case 2 appropriately disables screen content and is replaced by only an alertbox.
-  [x] Confirm Use Case 3 displays a warning alertbox as well as the associated screen content.'
-  [ ] _Confirm Error and Loading states still display as we would expect._ <-- NO LONGER part of this ticket

List of Screens:
  | 'WG_Health'
  | 'WG_Appointments'
  | 'WG_FolderMessages'
  | 'WG_PastAppointmentDetails'
  | 'WG_PrescriptionDetails'
  | 'WG_PrescriptionHistory'
  | 'WG_SecureMessaging'
  | 'WG_UpcomingAppointmentDetails'
  | 'WG_VaccineDetails'
  | 'WG_VaccineList'
  | 'WG_ViewMessage'
  | 'WG_PrepareForVideoVisit'
  | 'WG_StartNewMessage'
  | 'WG_ReplyMessage'
  | 'WG_EditDraft'
  | 'WG_Attachments'
  | 'WG_ReplyHelp'
  | 'WG_ConfirmContactInfo'
  | 'WG_RefillRequestSummary'
  | 'WG_RefillScreenModal'
  | 'WG_RefillTrackingModal'
  | 'WG_PrescriptionHelp'
  | 'WG_StatusDefinition'
  | 'WG_SessionNotStarted'
  | 'WG_Payments'
  | 'WG_PaymentDetails'
  | 'WG_DirectDeposit'
  | 'WG_HowToUpdateDirectDeposit'
  | 'WG_PaymentHistory'
  | 'WG_PaymentIssue'
  | 'WG_PaymentMissing'
  | 'WG_EditDirectDeposit'

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by TKDickson** [comment] 2023-11-20 13:54
Here's my full AF testing milestone, which includes these cases (Part 2).

Found #7335 while testing, not caused by AF code.

**Comment by TKDickson** [comment] 2023-11-21 16:59
Error handling/testing moved to ticket #7360 (aka not a part of this ticket)

**Comment by TKDickson** [comment] 2023-11-28 17:50
Added a number of screens from this ticket to #7282, also wrote up #7404.

As mentioned previously, error handling testing was moved to a later ticket. The only remaining testing left on this ticket is Use Case 1 for 'WG_RefillRequestSummary' and 'WG_RefillScreenModal', which is awaiting new refillable meds in staging for Karsyn.

**Comment by TKDickson** [comment] 2023-11-29 15:38
Got too excited about moving the other AF tickets; this one still has testing (see comment above) so scooting back to pre-develop with QA.

**Comment by TKDickson** [comment] 2023-11-29 15:59
OK - tested 'WG_RefillRequestSummary' and 'WG_RefillScreenModal', added another example to #7404 but nothing net-new. Testing complete!
Moving this ticket for real life to ready to merge (but it will wait with all of the rest of the AF tickets to actually merge)

**Comment by TKDickson** [comment] 2023-12-19 20:33
Spotchecked some Health and Payment screens; they are still enabled in develop. Closing.

**Closed** 2023-12-19 20:35 UTC
Labels: qa, front-end, global
