### ISSUE TITLE
BUG - Sev-3 - Android - Preferred name saved banner not appearing after saving the preferred name

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#7762] opened 2024-01-19 16:06 UTC
## What happened?

The preferred name saved banner is not appearing after saving the preferred name.

## Specs:

- Device: Android
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

1. Login to Judy
2. Navigate to the preferred name
3. Change the name a press 'Save'. Notice the 'preferred name saved' banner does not appear

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by cadibemma** [comment] 2024-02-12 09:30
Tried reproducing issue but was unable to replicate. Used Judy M. user and tested on android 11, 12, and 13 on Pixel 4 XL. Removing self from issue since I was unable to complete before OOO period.

**Comment by DJUltraTom** [comment] 2024-02-27 21:14
adding notes as I am seeing it on the nightly develop build, but inconsistently. seems to occasionally show the banner.
Google pixel 4A, android V13

**Comment by TKDickson** [comment] 2024-06-03 18:29
@theodur I'm pretty sure this was your change -- now I'm sitting on the [preferred name screen for long enough that I can cancel out of the workflow, but not _really_ cancel it of course](https://drive.google.com/file/d/1iP58UT_WF6T6R2WaapgCoVo-q2sJ_3pY/view?usp=sharing). You can end up with weird stuff depending on what sequence things hit your phone in.

**Comment by theodur** [comment] 2024-06-03 20:17
@TKDickson This is actually the current behavior in `develop`. This also isn't isolated to preferred name, other screens where we display a loading component and watch for back navigation (gender identity, rx refill screen, etc.) have the same behavior. This might be a UX topic, but I think it comes down to whether we want to allow users to attempt to cancel actions that are pending, because as long as we show the cancel button/watch for back navigation while the action is pending, there's not really a definitive way to control the outcome since it could be a race condition at that point. Either way, that's out of the scope of this ticket though

**Comment by TKDickson** [comment] 2024-06-03 20:24
In which case, keeping this ticket moving - approved to merge

**Comment by TKDickson** [comment] 2024-06-03 20:58
Doesn't require further testing, closing

**Closed by TKDickson** 2024-06-03 20:58 UTC
Labels: sev-3, bug, QA, front-end, Closed - Deployed/Fixed, scrubbed, Post Planning Add, global, QA 1
