### ISSUE TITLE
BUG - sev-2 - Android - Biometric login no longer works on Android 15

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#9925] opened 2024-10-21 13:37 UTC
## Submission from user

> Hello,
> I've been using the VA app for a while now and I've noticed there's a bug that makes my phone completely crash every time I try to log in using face cam detection. 
> 
> I have a pixel 8 pro and I'm using the latest full release android 15. I've been having this problem for over a month now while I was testing the beta version of Android 15.
> 
> Steps for bug:
> 
> 1- open app
> 2 - app tries to recognize my face for secure log in
> 3 - app doesn't do anything and freezes
> 4 - phone completely crashes and reboots
> 
> I only have the option of finger print scanner on my security settings in the app but it still uses my face. I think if the option says fingerprint it shouldn't even be using my camera for this.
> 
> This app is extremely important for me to manage my conditions so I would love for it to be fixed.

**Comment by TKDickson** [comment] 2024-10-22 19:55
My device has been attempting to update to Android 15 for over 24 hours at this point *sigh*. Still in progress on trying to reproduce.

**Comment by TKDickson** [comment] 2024-10-24 14:17
OK got Android 15 up on my pixel finally. I'm not seeing a crash, but I am seeing broken behavior - it's no stretch to me that this could crash in production/these are variations of the same root issue.

What I'm seeing is that biometric login silently fails (the biometric popup appears, I do fingerprint, and I'm eventually dropped back on the prelogin screen without an error message), but at that point, if I open up the webview to log in, I'm automatically signed in once I select my authentication option. I wonder if this is because I'm logging in before my session invalidates in the background, so I'm going to try to reproduce with using biometric authentication after more than 5 minutes after force-closing the app.

However, either way the failure of biometric login in Android 15 is a sev-2 bug (that will change over to a sev-1 bug reasonably soon as folks update their OS on their devices), so updating the ticket accordingly and will drop a note into the global channel.

**Comment by TKDickson** [comment] 2024-10-24 14:42
Should note that confirmed biometrics still worked on Android 14 (before I updated the device to 15), and also on my device running android 11.

**Comment by TKDickson** [comment] 2024-10-25 13:38
@theodur FYI I'll be doing QA on this (if/when we find it's fixable) since I'm the only one with a device on an OS high enough

**Comment by theodur** [comment] 2024-10-29 20:21
@TKDickson I don't have and Android device running 15, so I can't confirm the fix on my end, but the first place I started was updating the `react-native-keychain` package, which is responsible for retrieving the refresh token and prompting biometrics.

I made a [draft PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/10061) with the upgrade, and ran a [build](https://dsva.slack.com/archives/C022SV53ASZ/p1730227001092559) for it. I confirmed biometrics still works for iOS and Android 14. Could you confirm whether this build fixes the issue for Android 15?

**Comment by TKDickson** [comment] 2024-10-30 13:30
@theodur I tried biometrics four times - it failed the first time (same behavior as before), worked the next two, then failed the fourth. Both of the times that it worked, there was a fairly long pause (maybe ~5 seconds?) between the native Android biometrics popup disappearing, and the H&B app transitioning from the pre-login screen (with the 'sign in' and 'find a VA location' buttons) to the sync screen (with the 'signing you in' or whatever loading message).

This is probably an improvement (I tried biometrics.... probably about 3 times, and it failed all three, when writing up this ticket), but idk that I'd consider it fixed. I haven't been able to get charles traffic on my Android devices, but I know Tom can, so one option to help keep investigating is to check if he has a device that can go to 15, and could get logs of what's happening when the handoff from biometric login fails.

**Comment by theodur** [comment] 2024-10-30 17:30
@TKDickson Hmm, sounds like we're at least kind of heading in the right direction. Thanks, I'll sync with Tom and see if he can pull any logs from Charles

**Comment by theodur** [comment] 2024-11-07 18:14
@TKDickson I was able to upgrade my device to Android 15, and figured out a fix/workaround to the issue (more details in the [PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/10061) description). Since you're the only other person who can test this, can you test the changes in my branch and see if they work for you too?

Note: This will make more sense when you read the PR description, but if biometrics needs to be retried (especially twice or three times) there can be a long pause, which isn't ideal, but I made changes to at least show the `Signing you in` loading icon while biometrics is fetching the refresh token. While not ideal, this is probably the best we can do, since the time biometrics takes to retrieve the token is dependent on the `react-native-keychain` library.

**Comment by TKDickson** [comment] 2024-11-13 16:50
Tested all the cases I wanted to try, on my Android 15, and it's looking great:
* 5x immediate biometric login, they all worked (logged in successfully, and had loading screen whenever waiting)
* 1x time each for: 6 min wait, 17 min wait, 31 min wait. These all worked well too.

3 times (sprinkled throughout the above), I noticed that I was prompted for biometrics twice (and it worked the second time). I'm guessing that those would have previously failed, so this is an improvement for sure!

My less-than-Android-15 device's battery is dead and I didn't notice, so I'm recharging it to confirm that pre-Android-15 still has working biometrics, then will approve this ticket.

**Closed** 2024-11-13 20:24 UTC
Labels: sev-2, bug, front-end, user feedback, global, external-submission
