### ISSUE TITLE
guard against blank control_information field in payment information index endpoint 

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#9309] opened 2024-08-09 18:46 UTC
https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20AND%20resource_name%3A%22Mobile%3A%3AV0%3A%3APaymentInformationController%23index%22%20AND%20service%3Amobile-app%20AND%20%40http.status_code%3A500%20operation_name%3Arack.request%20status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=all&spanViewType=errors&view=spans&start=1722624302993&end=1723229102993&paused=false

https://dsva.slack.com/archives/C018V2JCWRJ/p1723228165838879

**Comment by kpethtel** [comment] 2024-09-05 21:37
This is a duplicate of https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9140, which I've been working on with Tom Harrison. AFAICT from our investigation so far, we shouldn't need to guard this because these fields should always be populated. It appears that the user isn't being found and lighthouse isn't handling it correctly.

**Closed by kpethtel** 2024-09-05 21:37 UTC
Labels: API team
