### ISSUE TITLE
Figure out if certain claims letters data happens in Prod

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7234] opened 2023-11-08 18:45 UTC
## Description 
As a [type of user/persona], I want to [goal/objective], so that [benefit/desired result/some reason].

As part of this story we want to:   
Figure out if the data inconsistencies that we saw in staging in #5892 (where a claim is stated to have a decision letter, but then no decision letter exists for it) can/does happen in Production.

This would essentially be if:
the total number of claims in the past claims call with `"decisionLetterSent": true` (v0/claims-and-appeals-overview)
does NOT match the total number of decision letters for the veteran (v0/claims/decision-letters)

- 

## Acceptance Criteria
  
Ideally we'd put in backend code to check for this happening in production

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by TKDickson** [comment] 2023-11-08 18:46
@jperk51 I had forgotten this would involve checking across two different calls (which may or may not both be called for any given user), so if this isn't something we can easily flag on the backend, feel free to just close the ticket.

**Comment by jperk51** [comment] 2023-11-08 18:53
Yeah that is a bit more complicated. We'll still consider it and see if we can come up with something that works, but there's a chance there's no real reasonable way to track this other than logging both instances and trying to manually tie them together

**Comment by aherzberg** [comment] 2023-12-12 16:04
merged, just need to enable flag and compare logs

**Comment by kpethtel** [comment] 2023-12-15 20:23
I believe that, yes, this error is happening in production. Per conversation with @TKDickson, i believe multiple issues may be going on. She says this is consistently failing for some users. I don't know why that would be. But I also suspect claims are sometimes not found somewhat randomly in production, perhaps due to a race condition. 

I changed the behavior for request decision from 500 to 404 when the claim is not found as part of [this ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7519). That's more correct and should improve monitoring. But I also believe we can improve the user experience by trying to refetch the claim in [this ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7564).

**Comment by kpethtel** [comment] 2023-12-18 16:20
See relevant comment from Charles here: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7519#issuecomment-1860664547

**Comment by aherzberg** [comment] 2023-12-18 16:37
Looks like it is a near guarantee that there will be mismatches between the decision letter sent boolean and the actual decision letters. Should be give this info to product and let them decide if we need to change the wordage to convey that information? the logs are now merged in but I haven't enabled them yet. Do we still think it's worth parsing through the logs to match up users now that we know it's part of the business logic? I talked with Jerek on the benefits team and he said the decision letter sent boolean from the claims index is a black box to them and they are planning to figure out exactly how it's determined but don't know right now.

**Comment by jperk51** [comment] 2023-12-18 16:50
We should enable the logs for a few days just to have some records if we need them, but yeah let whoever is now responsible for claims know what's going on tag me on it and collectively we'll figure out how we want to handle it.

**Comment by aherzberg** [comment] 2023-12-18 19:32
sounds good. Set logging to 1% of prod users

**Comment by jperk51** [comment] 2023-12-19 16:25
@aherzberg were the logs able to confirm that the cause was what Charles stated in the comment Kris linked?

**Comment by aherzberg** [comment] 2023-12-19 16:34
I'm not positive on the forms here but Charles was refering to depedency decision letters while our decision letters are only 184 (VA 20-8993, VA 21-0290, PCGL) which are different I think? I think the business rule that a decision being reach is not equal to a decision letter is holding true even for the 184 forms though.

**Comment by aherzberg** [comment] 2023-12-20 00:11
reopened #5892 for product/UX to decide how to proceed. closing this ticket.

**Closed by aherzberg** 2023-12-20 00:11 UTC
Labels: back-end, claims & appeals
