### ISSUE TITLE
Component App Propagation - Link (Global)

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6868] opened 2023-09-28 13:08 UTC
## Description

This ticket needs to be sprint-aligned with the Global App team to be able to offer support, collect feedback, and make needed changes to the ClickForActionLink component package for App Propagation. Due to the nature of this ticket, the work will likely carry over multiple sprints.

## Important links

- [npm package](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library)

## Definition of Done

- [ ] The Mobile app team has been alerted to the existence of the new component
- [ ] Areas of the the app that need to be updated have been communicated and documented
- [ ] The new ClickForActionLink component is implemented in all areas of the app
    - Should also be able to replace:
       - ClickToCallPhoneNumber
       - AttachmentLink (partially)
       - One-off built "links" that are just text styled to look like links (e.g. updating your D.O.B. in Profile and anything else that opens in-app)
    - May also allow cleaning up utilities relating to Directions type links/opening external links generally
- [ ] The Mobile apps have been released to their respective app stores with the component installed

**Comment by TimRoe** [comment] 2024-03-01 17:09
Updated ticket to reflect the Link component should be capable of replacing more than just `ClickForActionLink`.

**Comment by cadibemma** [comment] 2024-05-10 23:48
This has been handled in tickets [7687](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7687) and [7688](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7688). Checked around and didn't find any that was missed. Closing issue.

**Comment by TimRoe** [comment] 2024-05-13 21:53
@ajsarkar28 (cc: @kellylein) Should this ticket be reopened? Doing a quick search of `"link"` on the app gets 12 hits of pressable components with an `accessibilityRole` value of link.

These are some of (not all) instances of this AC that was not completed by the tickets mentioned above:
> One-off built "links" that are just text styled to look like links (e.g. updating your D.O.B. in Profile and anything else that opens in-app)

Others may be found looking for Text components using the "link" color from the app-level theming, looking for textDecoration "underline", and others. For example, a hit not in the previously mentioned 12 appears on MilitaryInformationScreen.tsx searching for `'underline'`.

If relevant, the initial 12 hits are spread between: Profile, Payments, and Secure Messaging so there's global and H&B spots.

All of these fake "links" should be replaceable by the design system Link component.

**Comment by cadibemma** [comment] 2024-05-28 08:40
For `ClickToCallPhoneNumber` and `AttachmentLink` the Link component  is implemented within these components. The `ClickToCallPhoneNumberDeprecated` is still used for the VeteranStatus Screen because it uses the colorOverride prop which the Link component lacks.

**Comment by TKDickson** [comment] 2024-06-04 19:13
Manually checked iOS contact info, payment list & details, personal info in demo mode iOS. Was seeing something weird (add to calendar wasn't doing anything) so wanted to check - still want to check - a staging user, but was getting 503s back from upstream just trying to load appointments in staging, so will need to loop back to that.

Also have [detox running for Android.](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/9372796098)

**Comment by TKDickson** [comment] 2024-06-04 20:06
Yeah add to calendar isn't working on my iOS, wrote up #8788 and also confirmed it was in develop as well.

**Comment by TKDickson** [comment] 2024-06-05 13:39
Pulled the junit file override fix (from develop) into this branch, and attempting [the detox run again.](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/9385191919)

**Comment by TKDickson** [comment] 2024-06-05 16:15
All passed except Contact Info (and contact info seems to have shorted out on a GHA issue, not code/UI issue) so [running just that one again.](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/9387642704)

**Comment by TKDickson** [comment] 2024-06-07 13:34
Woo! That one passed; this is ready to merge.

**Comment by TKDickson** [comment] 2024-06-07 15:17
Doesn't require further testing in develop, closing

**Closed by TKDickson** 2024-06-07 15:17 UTC
Labels: QA, front-end, mobile-platform, global, QA 1
