### ISSUE TITLE
Veteran's Health Identification Card (VHIC)

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#5122] opened 2023-03-15 20:02 UTC
# Epic/ Project Status - ON HOLD

**Project Overview**:
User Story: As a Veteran, I want to be able to show that I am covered with VA Health Services Benefits using VIC

Note: This is separate from Veteran Status (VSC) (Formally VIC). This is what the Vet receives when they are enrolled in healthcare.  This can card can also be used for proving the person is a Veteran, etc.

**Team Members**

- **OCTO Product Leads:** Rachel Han

- **Ad Hoc PM:** Stacy Blackwood
- **Engineering Lead:**  Jason Conigliari

- **Design:** TBD

**Discovery Spike Information (minimal information)**- reference **comments** section in [THIS](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6392) ticket for schema and metrics given so far. Note: This project was put on HOLD

**Product Outline**: TBD (Will be based on Discovery Output and MVP Responses)

## Monthly Update
|Month| Project Health|Progress & Key Accomplishments| Issues/Risks/Blockers| Comments
|-------| ---------|--------|---------| ------|
|Aug '23| Yellow  BLOCKED- VA compliance to start Discovery

**Comment by StacyB2023** [comment] 2023-09-06 19:39
@kellylein Do you know what this "error rendering markdown" means? I'm not able to see full information anymore in this epic or the ticket 6392

**Comment by StacyB2023** [comment] 2023-09-06 19:49
Moved this epic status to blocked. We are currently awaiting progress/responses to start Discovery. Will be considered for future Quarters.

cc: @Hallm13

**Comment by StacyB2023** [comment] 2023-09-06 19:50
@kellylein Just an FYI that i've moved this to "later" column on Kanban. Not sure when we would revisit this. Based on VA compliance

**Comment by rachelhanster** [comment] 2023-10-31 17:19
@chrisj-usds and I to follow up with Health Eligibility Center, VHA and OIT/IAM teams, investigate then decide if OCTO pursues this initiative

**Comment by ajsarkar28** [comment] 2023-12-27 03:23
This is now a separate team and contract. Closing epic

**Closed by ajsarkar28** 2023-12-27 03:23 UTC
Labels: Epic, back-end, Health, mobile-blue-team, crew-mobile-app, roadmap-DMC

**Comment by chrisj-gov** [comment] 2025-08-04 20:38
Closing as duplicate of: 
https://github.com/department-of-veterans-affairs/digital-experience-products/issues/1403
