### ISSUE TITLE
Migrate prescription to React Query

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#6730] opened 2023-09-13 19:39 UTC
## Description

The state for prescription data in the app is managed in the Redux store, specifically in the [prescriptionSlice](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/store/slices/prescriptionSlice.ts#L0-L1). This slice is a good candidate for being migrated to React Query. The API calls can be moved into a separate directory in the [src/api](https://github.com/department-of-veterans-affairs/va-mobile-app/tree/develop/VAMobile/src/api) directory, e.g. `src/api/prescription`. An example can be seen in this PR: https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6627

## Acceptance Criteria
- [ ] Migrate all the API calls in the prescription slice to queries and mutations
- [ ] Update the necessary screens and components to use the new queries and mutations

**Comment by rbontrager** [comment] 2024-03-14 12:51
@Sparowhawk A couple things:
1. The app is crashing when you press the 'start refill request' button in the prescriptions page. 
2. If you go to an active prescription with refills, tap 'request refill', tap 'request refill' again its going to the refill request page (with all the prescriptions available for refill) instead of doing the refill request and sending you to the refill request summary page.

**Comment by Sparowhawk** [comment] 2024-03-14 17:15
should all be fixed now

**Comment by rbontrager** [comment] 2024-03-26 14:18
Verified that the app/detox tests still work as intended.  Verified that the app no longer crashes on refill request.  Approved by QA.

**Closed by rbontrager** 2024-03-26 14:18 UTC
Labels: front-end, Health, code upkeep
