### ISSUE TITLE
Update to Gender Identity large panel content

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8068] opened 2024-02-26 19:32 UTC
## Description 
Per [this web team ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66577#event-11642270878), the VA.gov Profile has updated some content around what a Veteran should know before they share/update their gender identity on VA.gov.

**Update 3/13/24:** The [shipped files in Figma](https://www.figma.com/file/O6sdr5N7xV6GOZhTPcgY5x/%F0%9F%9A%A2-Profile-2.0---Shipped---VA-Mobile?type=design&node-id=834-13772&mode=design&t=kZ51maSrSm7AbpE3-4) have been updated with the new copy. ENG should be able to grab the updated copy from there. Please follow the formatting as it aligns with VA.gov.

## Current in Mobile App
[Link to our Figma file](https://www.figma.com/file/O6sdr5N7xV6GOZhTPcgY5x/%F0%9F%9A%A2-Profile-2.0---Shipped---VA-Mobile?type=design&node-id=834-13614&mode=design&t=Z0xzQMlyj4iouTFi-4) and screenshot of full current copy below.
<img width="212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzZPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0ca1e63467d414ef095c8b4d0964b56130f6a83/Screenshot%202024-02-26%20at%202.25.31%E2%80%AFPM.png" alt="Screenshot 2024-02-26 at 2.25.31 PM.png" />

## Web's New Content
[Link to Figma file](https://www.figma.com/file/qfyUmEOVawplgrEKYKFp0f/Profile---Personal-information?type=design&node-id=0-17&mode=design&t=OqMbwLn2y7nnElD0-4) and screenshot below
<img width="165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEtPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3766d622f389a3d191c5e96165b48a1b1b318013/Screenshot%202024-02-26%20at%202.29.48%E2%80%AFPM.png" alt="Screenshot 2024-02-26 at 2.29.48 PM.png" />

## Acceptance Criteria
  

-  [x] **Brea:** Update shipped files with new copy
-  [x] **Brea:** Update ticket with link to updated shipped file and move ticket to backlog

**Comment by brea11y** [comment] 2024-03-13 18:12
The [shipped files](https://www.figma.com/file/O6sdr5N7xV6GOZhTPcgY5x/%F0%9F%9A%A2-Profile-2.0---Shipped---VA-Mobile?type=design&node-id=834-13772&mode=design&t=kZ51maSrSm7AbpE3-4) have been updated with the new copy.

**Comment by mistymg** [comment] 2024-03-15 11:13
Thanks @brea11y! I edited our copy just a tad in the shipped files to remove mentions of "VA.gov profile" since they're in the app. Otherwise ready for Eng!

One last note: That external link at the bottom of the large panel should take the Veteran to the VA location finder page: https://www.va.gov/find-locations

**Comment by TKDickson** [comment] 2024-03-26 16:57
Looks like there's an extra carriage return in the first bullet point (after the bolded portion of the line). <img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86a0ce4f50d8f4c1658501f9509d52b7b880a0fb/image.png" alt="image.png" />

Will confirm in Slack that this is not intended.

**Comment by TKDickson** [comment] 2024-03-26 17:03
Confirmed with Misty, that should all be a single line. Sending back for minor change, the rest matched design & met accessibility standards.

**Comment by TKDickson** [comment] 2024-03-26 17:03
FYI @cadibemma ^

**Comment by TKDickson** [comment] 2024-03-26 17:49
Fixed! <img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK01RQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--498b4979fc162ed59ee0d6e931ff956d53ae58ca/image.png" alt="image.png" />


Running the Personal Info detox script, iOS and Android, for this change. I'm not anticipating any issues, so when those come back clean :fingers-crossed: then I can approve this PR.

**Comment by TKDickson** [comment] 2024-03-26 18:44
[iOS worked great](https://dsvavsp.testrail.io/index.php?/runs/view/5352&group_by=cases:section_id&group_order=asc); [Android also mostly pass](https://dsvavsp.testrail.io/index.php?/runs/view/5354&group_by=cases:section_id&group_order=asc) (and the things that failed are not this branch's area).

Approving PR merge.

**Comment by TKDickson** [comment] 2024-03-26 23:29
No further testing needed in develop, closing

**Closed by TKDickson** 2024-03-26 23:29 UTC
Labels: QA, front-end, global, QA 1
