### ISSUE TITLE
Update In-App Review Code to Include New Features

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#9221] opened 2024-07-30 14:08 UTC
AC:

Update the In-App review event actions to include the following events:
- Viewing a decision letter
 - In Profile:
    - Viewing disability rating screen
    - Editing or adding preferred name
    - Editing or adding gender identity
- In Prescriptions:
  - Viewing the detail page for a medication
  -  Viewing the tracking detail page for a medication
   - Successfully submitting a refill request for medication(s)
- In Payments:
   - Editing or adding a direct deposit account
  - Viewing payment details
- Viewing veteran status card 

For addition details, see the [sprint 0](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/In-App%20Review%20Updates/InAppReviewUpdates.md)

**Comment by TKDickson** [comment] 2024-08-05 20:59
Planned [test run](https://dsvavsp.testrail.io/index.php?/runs/view/5798&group_by=cases:section_id&group_order=asc). 

@DJUltraTom this is ready for test plan review. I added steps 22 onward for the happy path cases (and just cleaned up the navigation for the existing cases, which was using pre-Nav stuff, while I was in there), and wrote up the API failure case. Basically anything I find in the API failure case, and steps 1-21 of the happy path case, will be new bug tickets instead of on this ticket, but I don't think anyone has tested these in a long time, so I'm going to add on the time.

**Comment by DJUltraTom** [comment] 2024-08-05 22:43
QA peer review notes:
for step 2 of the API failure case should we update the link to point to the updated test plan you wrote? (1260650 vs 12097)
Are you planning for an a11y test pass?

**Comment by TKDickson** [comment] 2024-08-06 15:21
@DJUltraTom 
1. Yep I will update that link.
2. No, I'm not adding accessibility passes to the run. All of the changes are behind-the-scenes code. Although I might find accessibility issues if I tested with assistive technology, they would all be pre-existing. Given that in-app review is already a fairly lengthy thing to test (because you have to constantly set up and destroy the in-app counter), I've already added some scope to cover other risky & not-caused-by-these-changes areas that I think are a bigger risk (see original test plan comment), and that the in-app review pop-up itself is entirely not within the app's control, I'm not planning on doing full accessibility passes. That being said, I always turn on a screen reader at least once during pretty much any testing, so if there's a screen reader trap or some other glaring pre-existing bug, I'll catch that even without those explicit cases.

**Comment by TKDickson** [comment] 2024-08-07 20:31
Found #9289 while testing (not caused by these changes - also I'm not surprised, since in a meeting with Binny he mentioned that he didn't see the code for incrementing it, in details).

**Comment by TKDickson** [comment] 2024-08-09 14:19
OK; I've been having Charles Proxy weirdness which has blocked some of my planned testing (making sure that events that fire on APIs, only fire when the APIs are successful) - however, when I took a step back I realized that's not in the required testing scope for this ticket. I'll write a ticket for 'investigate what happens in that scenario' that I will put into the appropriate backlog - and this one is OK to merge.

**Comment by TKDickson** [comment] 2024-08-09 15:51
Doesn't require further testing in develop; closing

**Closed by TKDickson** 2024-08-09 15:51 UTC
Labels: front-end, global, QA 3
