### ISSUE TITLE
CU - Availability Framework Style BE Error Handling/Customization

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#8603] opened 2024-05-10 13:08 UTC
## Proposed Change

We need to intercept BE status 418 codes and display a custom error response to users given the following documented data properties: [link](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Features/CustomErrorResponses).

In basically all ways this is similar to AF simply being triggered by the API response as opposed to a remote config setting retrieval.

## Why Should We Prioritize?

This will allow us some pretty wide and deep error and issue handling response outside of app store updates once live.

## Coding Time Estimation

3	

## Testing Considerations

Ensure using a specific test staging user that we can receive this accurately displayed error message from the BE response on several endpoints. 

## Checklist
- [ ] Add the relevant team label (Health, global, etc.)
- [ ] Attach to the [Engineering Initiatives (Frontend)](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5139) epic

**Comment by TKDickson** [comment] 2024-06-25 21:35
Added the blocked-qa label; this is not a ticket I'm actively working on (sprint priorities)

**Comment by TKDickson** [comment] 2024-07-05 14:23
@cadibemma @dumathane who is the specific staging user that's flagged for testing this?

**Comment by TKDickson** [comment] 2024-07-05 14:27
**QA time estimate**
Creation of test cases (plan below) + test plan review + manual testing: 3 points
* Correctly handling 418 response (showing custom error) for flagged user + new client
* Also - presumably - showing custom error for non-flagged user + new client + 418...?
* Showing old error message for flagged user, 418, and old mobile client
* Showing old error message for flagged user, non-418, and new mobile client
Creation of new detox script (which will involve changing the mock data, which I don't know how to do yet) for this: also 3 points

**Comment by TKDickson** [comment] 2024-07-10 15:25
[Planned test run for custom BE error handling](https://dsvavsp.testrail.io/index.php?/runs/view/5704&group_by=cases:section_id&group_order=asc); the new cases that need to be reviewed by QA are all of them except the a11y ones.

**Comment by TKDickson** [comment] 2024-07-10 15:52
Removing the blocked-qa label, I'm going to attempt to make (slow) progress on this, this sprint. It's essentially the thing I'll pick up when/if time.

**Comment by DJUltraTom** [comment] 2024-07-10 22:11
Reviewed and have the following suggestion/question:
- Call out tapping the TTY(if included) separate from the telephone number test step
- The mock ups do not have an area for text entry field, is the "field testing Standard Cases" applicable for validation

**Comment by TKDickson** [comment] 2024-07-11 16:59
Found #9054 while testing; not caused by this development

**Comment by TKDickson** [comment] 2024-07-11 19:40
On Android, with an updated or OLD mobile client (today's develop build; or any mobile client that does NOT include Chika's change), the custom response from the BE for user +141 results in the same freeze/lag problem as in #7746. Since this particular user is set up with the appts call, that lag is happening on onboarding, then home, then health, then appointments itself - and anytime you access any of those pages subsequently, as well. 

I feel like this is probably a dealbreaker - sending this back to @cadibemma for investigation into whether its the same/a similar root issue as the other one (in which case we'd want to ask the BE team for a different format, maybe?). FYI @dumathane as well because I know you've been watching for this.

**Comment by TKDickson** [comment] 2024-07-31 20:39
Able to finish up initial testing pass on this. Does exactly what it says on the tin, currently, but I think that we probably want a little more special character support (critically, apostrophes) - I'm going to ping about it in Slack.

Otherwise, this is functioning as expected, minus the lag we weren't able to address from the comment above.

**Comment by TKDickson** [comment] 2024-08-01 13:49
Add apostrophe support (needed for MVP per @mistymg). With that in, I'd approve.

**Comment by TKDickson** [comment] 2024-08-01 15:54
Also - and I forgot about this when I said "apostrophes are the last thing" earlier - you'll need to write a detox case for this, @cadibemma . We have the ability to swap in a different file/mocked response via detox (I haven't written one personally but have done PR review for Rachael's ones where she has), so swapping in a 418 response, making sure we're showing the custom response and not the generic error response, and the resetting the app.

**Comment by cadibemma** [comment] 2024-08-08 17:30
Will need to work with @rbontrager to see if its possible to mock error responses - moving to blocked

**Comment by cadibemma** [comment] 2024-08-13 16:21
Currently there isn't a simple way to test/create errors on detox, so ticket [9348](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9348) was created.
-Now unblocked

**Comment by TKDickson** [comment] 2024-08-14 16:51
Doesn't require testing in develop; closing

**Closed by TKDickson** 2024-08-14 16:51 UTC
Labels: front-end, code upkeep, global, QA 8
