### ISSUE TITLE
Create Activity Section with Populated, Loading, and Empty States

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7935] opened 2024-02-07 18:25 UTC
**Overview**
This ticket covers the creation of the home screen's activity section with the populated, loading, and empty states. The error and edgecases are covered in this [ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7937).

For all visual elements in this ticket, reflect the designs in this [Figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=2723-916&mode=design&t=iNmoPBQvnErOJAu5-4)

**Header**
- A header that says Activity, using the designs in , is implemented. Home screen buttons only appear after this header

**Populated**
- If a feature module has data returned from the backend, then it is displayed on the home screen

**Loading** 
- While the backend is returning feature module data, display the loading UI
- Once the backend has returned data for any feature module, do not display the loading UI

**Empty State**
- If no data has been returned from the backend for any feature module, then display the empty state UI

**Accessibility & Content** 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by TKDickson** [comment] 2024-02-20 15:35
[Test case link in TestRail](https://dsvavsp.testrail.io/index.php?/cases/view/59376)

**Comment by theodur** [comment] 2024-03-07 18:29
@TKDickson Heads up, I had to make minor changes to the loading component on the View message screen. I confirmed there are no breaking changes to that screen, but wanted to let you know just in case. Here's more context if you're curious:

Originally, there was an `inlineSpinner` prop that was added to the `LoadingComponent`, and basically all it did was remove the contents of the `LoadingComponent` out of the `VAScrollView` that wraps around it. This was needed so that the background color of the loading component matched the background of the View message screen (since it uses a different background color than other screens in the app). Here's a [video](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8098#discussion_r1513638975) of what the prop was doing. 

I wanted to use the `inlineSpinner` prop to render the spinner next to the text (like how we need it for the activity section), so I updated up the `LoadingComponent` to accept a new prop `scrollViewStyle` that allows for modifying the style of the `VAScrollView`. This way, instead of conditionally removing the loading component content out of the scroll view just to match the background color of the screen, we can manually pass the background color to the loading component

**Comment by TKDickson** [comment] 2024-03-08 14:01
* Checking with UX about the screen reader interaction in this section, I can't tell if the icon should be read with everything else, or if the icon is meant to stand alone.
* The loading indicator isn't currently read as 'loading' but should be according to the Figma annotation (which I realize may involve changing ALL loading indicators in the whole app, so if that's the deal let's chat about it with the team first)
* We're (over-showing? mistakenly showing?) a Cerner-specific message when a patient has no activity buttons. See [the Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=e4c23f18-0146-44eb-91a4-280463fda389), column 2B (vs what we're currently showing, which is a mix of 2B and 5A/B). I'm using +226 who is not a Cerner patient/has no Oracle Health sites.

**Comment by TKDickson** [comment] 2024-03-08 14:43
Ah, shoot. We super-broke messaging details by messing with the spinner.

Here's [the behavior loading a message with attachment(s) from a thread in message details, in develop.](https://drive.google.com/file/d/1BQo9Mok12Ux9J9PpeGc-73unhCOaxwAA/view?usp=sharing)
Here's [the behavior in this branch](https://drive.google.com/file/d/1N37fsWXn__CdynPrv1AcYvQdWUJMiOgQ/view?usp=sharing) (note the change in location after load, plus the message you're trying to open is still collapsed when you get back down to it and you have to open it again)

+226 has messages with threads/attachments (the first one in the inbox list should work for you) to check this out.

**Comment by theodur** [comment] 2024-03-11 23:15
Nice finds @TKDickson! Just fixed all of these, should be good to test again

**Comment by TKDickson** [comment] 2024-03-12 15:07
@theodur sending back your way for a couple things

Message details loading behavior (spinner & the rest), as well as reading [icon + text] for both loading and empty states, are now both fixed.

* Still showing the extra Cerner message on empty state (screenshot, circled in purple)
* The empty state is now reading out an extra "right brace" along with the intended text, which I think you can mostly see in the caption on the second screenshot.

<img width="377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzdTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--679fee8331b2bc7881044eb2718c59e4385e7dc3/image.png" alt="image.png" />

<img width="377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzNTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16929b8d1c0268e90b2b5dc35b2f215767889f5b/image.png" alt="image.png" />

**Comment by dumathane** [comment] 2024-03-12 16:06
fixed! Back to you @TKDickson

**Comment by TKDickson** [comment] 2024-03-13 15:04
[belated test run link](https://dsvavsp.testrail.io/index.php?/runs/view/5291&group_by=cases:section_id&group_order=asc)

**Comment by theodur** [comment] 2024-03-13 21:00
I updated the margins for the alert statuses as discussed in Slack ([thread](https://adhoc.slack.com/archives/C063KLSMVAR/p1710339100747509)). Went ahead and updated the margins for the `About you` section's alert statuses too, since those also had the 10 px margins. Here's what it looks like for reference:

<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/e023ab06-c62d-48d3-93cb-f3514213f50c" width="49%" />&nbsp;&nbsp;<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/d88dbe97-600b-494d-94e0-fee347091e31" width="49%" />

**Comment by wavelaurenrussell** [comment] 2024-03-14 16:44
Thank you. Reviewed the changes – looks good!

**Comment by TKDickson** [comment] 2024-03-14 16:56
merged to xl and closing

**Closed by TKDickson** 2024-03-14 16:56 UTC
Labels: QA, front-end, global, QA 1
