### ISSUE TITLE
Copy updates to downtime/maintenance windows

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8067] opened 2024-02-26 19:10 UTC
## Description 
We want to update the copy for our maintenance windows to be more explicit that why a Veteran can't access a part of the app is that we're doing maintenance vs the app isn't working. We also want to remove the dynamic feature name from the body copy so as to future-proof our content and make sure it makes sense no matter the feature name. Finally, we want to give the users a way to get done what they came to the app to do. Currently there's no CTA for our maintenance windows. We should give users at least one way to do what they came to the app to do.

Current copy:
"downtime.message": "{{featureName}} on V\ufeffA mobile app is currently unavailable. We're working to fix this. We intend to restore this by {{endTime}}. Please check back soon."
"downtime.title": "Some online tools or services aren't working right now"

## Acceptance Criteria
  

- [ ] Alert header copy: Maintenance on mobile app
- [ ] Alert body copy line 1: We're working on this part of the mobile app right now. We'll be done by [endTime].
- [ ] Alert body copy line 2: If you need help, call our main information line. We're here 24/7.
- [ ] Phone number link: 800-698-2411
- [ ] TTY link: TTY: 711

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by TKDickson** [comment] 2024-04-01 18:29
Edited [the maintenance window test case](https://dsvavsp.testrail.io/index.php?/cases/view/33977&group_by=cases:section_id&group_order=desc&display_deleted_cases=0&group_id=8943) to reflect the new content

**Comment by TKDickson** [comment] 2024-04-04 17:26
Spacing is fixed! Android isn't including the 'at' in the date-time display, like iOS is. I bet it's a platform difference *sigh*

Maintenance window banner on the messages screen, on an Android device. The key sentence is "We'll be done by April 24, 2024, 2:15 PM CDT" which should instead read "We'll be done by April 24, 2024 at 2:15 PM CDT"

<img width="361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2syQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b10375484ff57a33a9e86facb35023e716acaef/image.png" alt="image.png" />

**Comment by TKDickson** [comment] 2024-04-04 21:20
"at" is included in iOS and Android, and spacing is still good. 

Found #8310 while testing (not caused by this development, I confirmed I can reproduce in the 2.25 RC branch). 

Approved to merge to develop.

**Comment by TKDickson** [comment] 2024-04-05 19:34
Do not need to test again in develop, closing.

**Closed by TKDickson** 2024-04-05 19:34 UTC
Labels: QA, front-end, global, QA 1
