### ISSUE TITLE
BUG - sev-2 - Android - Login workflow sporadically not allowed on OnePlus+Firefox

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7008] opened 2023-10-16 19:29 UTC
## What happened?

On my OnePlus device with Firefox as the default browser, when testing the fixes to #6986 and #6985, I found that sporadically, about 30% of the time, [my Firefox window would blank out when appswitching back to complete 2FA](https://drive.google.com/file/d/1bBSq8ipbjPm018ZDF_d4fMrj4fHVXZou/view?usp=sharing).

Login on other browsers on that device (Chrome, Firefox), and login on all other browsers & devices attempted (Pixel 3, Pixel 6, Galaxy S7 - Firefox, Chrome, Samsung Internet, Opera) succeeded every time.

## Specs:

- Device: OnePlus
- OS: Android 11
- User Account: any
- Accessibility State: n/a

## Steps to Reproduce

See linked video in problem description. When doing that exact workflow 10 times in a row, it failed 3 times and worked 7, in this order: S F S S F S F S S S

## Desired behavior

Login should work every time

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High 
- Frequency: Low 

- 2 - High

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by alexandec** [comment] 2023-11-01 21:22
I think a OnePlus emulator would be required to reproduce this, or an actual OnePlus device. I don't have a OnePlus device and I was unable to find any OnePlus emulators in my searching. I don't think we can work on this bug without being able to reproduce it, because it's specific to a single device/browser combination. Because of that I don't think we have a path forward currently on this bug.

**Comment by TKDickson** [comment] 2023-11-02 15:11
Bah, I forgot that Android + Charles doesn't work during authentication (iOS + Charles does, spooky). Can't provide an assist here, unassigning.

**Comment by bischoffa** [comment] 2023-11-07 16:13
@TKDickson given this are you okay with either icebox or closing?

**Comment by dumathane** [comment] 2023-11-07 16:22
Closed due to testing constraints.

**Closed by dumathane** 2023-11-07 16:22 UTC
Labels: sev-2, bug, front-end, scrubbed
