### ISSUE TITLE
Home Screen Module Logic - Appointments

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7379] opened 2023-11-23 17:25 UTC
**Background**
* This ticket covers the content and display logic for the Appointments module which displays on the home screen

**Acceptance Criteria**
* If the Veteran has upcoming Appointments, based on the backend work in the ticket in the comments, then display a module on the home screen with the following content:
    * Text that says “Appointments (x upcoming)” 
        * In this example, x should be replaced with the number of upcoming appointments returned from the backend. For instance, if the Veteran has 2 upcoming appointments, the module will read “Appointments (2 upcoming)” 
    * If clicked, the module should deep link the user to the Appointments page
 * If the Veteran has 0 upcoming Appointments returned from the backend, then do NOT display an Appointments module
 * NOTE - error handling is not finalized and will be covered in a separate ticket (ex. health) not feature level (ex. just prescriptions)
 * NOTE - This ticket is strictly display logic. The UI will be covered in a separate ticket once designs are finalized

**Comment by ajsarkar28** [comment] 2023-12-04 19:18
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7211

**Comment by TKDickson** [comment] 2023-12-05 21:29
QA estimate - 2 points (mostly spent digging through the various staging users to find people to test things). _For instance, want to test a user with a pending appt in the next 14 days_

**Comment by TKDickson** [comment] 2023-12-12 15:16
Confirm the correct display number for users who have (in the next two weeks):
- [ ] 0 confirmed appointments 
- [ ] at least 1 confirmed appointment 
- [ ] at least 1 pending appointment 
- [ ] at least 1 cancelled (previously confirmed) appointment
- [ ] an appointment missing a start or end date, if I can find one (TBD appointment, if the concept exists at VA)
- [ ] an appointment that's happening TODAY but earlier in the day

For a user who has the appointments module displaying (1+ confirmed appts in the next two weeks):
- [ ] when I tap on the appt module, it navigates to the appointments list
- [ ] when I tap 'back' at this point, it.... goes back to the home screen?

**Comment by TKDickson** [comment] 2023-12-15 16:30
Alright, everyone IGNORE that test plan in the prior comment. Due to issues (not bugs, but different ways people thought appointments would work and how we hammered out we want appointments to work, see #7556) I am moving all of the 'backend logic testing' to ticket #7533. 

This ticket will cover SOLELY the ugly UI, basic functional testing. Test plan in the next comment.

**Comment by TKDickson** [comment] 2023-12-15 16:32
Actual test plan:

- [ ] User with AppointmentCount of 1 or more (mock it if needed) - appointments module shows up on the homescreen, with the correct # displayed
- [ ] User with appointmentCount of 0 - the appointments module does not appear on the homescreen


For a user when the module appears on the screen:
 wh

- [ ] en I tap on the appt module, it navigates to the appointments list
- [ ]  when I tap '< Health' at this point, it navigates to Health category landing
- [ ]  or if I tap on the built-in back (Android back button, iOS swipe), it navigates to the Health category landing

**Comment by TKDickson** [comment] 2023-12-15 16:58
Most of this is working appropriately; an appointment count of 0 crashes the app or throws a red-screen error (Android). Moving back to the in-progress column for @theodur to take a look next week, and just FYI @ajsarkar28

**Comment by theodur** [comment] 2023-12-18 22:37
@TKDickson Was there a specific user you saw the Android crash with? I just tried with the user you mentioned in the PR (kidys.b.quankep@id.me) and I'm not seeing a crash. Here's what I'm seeing:

[AndroidAppointmentsModule.webm](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/71cd5be9-847d-4220-bc3c-b46877b07cfa)

**Comment by TKDickson** [comment] 2023-12-19 15:14
Bizarre. @theodur I'm getting red screen of death for kidys (fresh build, real device) on Android still this morning. Specifically this red screen of death #7565. On iOS it just crashes. I was able to log in successfully (no crashes or errors) with a couple other VAOS staging users who had appointments (claudia and grethel)

Any chance it's a device vs simulator thing? I'm using my Google Pixel.

**Comment by theodur** [comment] 2023-12-19 16:46
Hmmm that's so strange. I wouldn't expect it to function differently on a physical device, but it sounds like that's the main difference between our environments when we're testing 🤔. Can you point me to the build you're testing on? I'll try on my devices and see

**Comment by TKDickson** [comment] 2023-12-19 17:19
@theodur or we're just having one of our 'fun' device mismatches again! I'm testing on a build from a week-ish ago, commented "7379 homescreen appts"

**Comment by theodur** [comment] 2023-12-19 20:13
Just confirmed on a new build that the issue is resolved, I moved this back to `With QA`

**Comment by TKDickson** [comment] 2023-12-19 21:49
Yep, I missed somehow that I needed to make a new build (facepalm).

But! Also testing on a build with the fix, this is no longer crashing. Added notes to feature signoff ticket, and closing this ticket/approving to merge into feature XL

**Closed by TKDickson** 2023-12-19 21:49 UTC
Labels: qa, front-end, global
