### ISSUE TITLE
Veteran Status - In-App Whats New Content 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6539] opened 2023-08-18 14:44 UTC
Purpose:

- Determine What's New In-App alert box content

Other info:

- [MVP Figma File ](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?type=design&node-id=1806-90255&mode=design&t=BMeiQdH7AJlwuT6j-4)

Open question:
Also need content for app store what's new sections? 
When is this being released?
With what else is this being released?

**Comment by bischoffa** [comment] 2023-08-18 14:45
@mistymg I removed some points from Travel Reimbursement as it will not be needed this sprint per convo with Matt, so with that I took a point for this. Given POs wanted to move forward to implement the work we wanted to call it out in Whats New In App Alert Box. 

Note MVP has changed slightly as there is no photo. Above is the new MVP Figma file.

**Comment by mistymg** [comment] 2023-08-21 15:43
Closing this ticket as it's a duplicate of 6548

**Closed by mistymg** 2023-08-21 15:43 UTC
Labels: ux, content
