### ISSUE TITLE
Remove source from appointments error response

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#9512] opened 2024-08-29 18:22 UTC
The front end is experiencing crashing while parsing the error source information. Front end bug ticket is [here](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/4762).

AC:
- errors similar to those in the ticket do not include source information
- we also add `source: 'VA Service'` when partial errors are received from upstream. That is still needed in order to indicated to the user that some data may be missing. This should not be removed.

**Comment by jperk51** [comment] 2024-09-05 18:26
Close as duplicate of #9510

**Closed** 2024-09-13 14:45 UTC
Labels: API team
