### ISSUE TITLE
BUG - sev-3 - All - Add heading/change template for first time login interstitial screen

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5129] opened 2023-03-16 19:48 UTC
## What happened?

For maximum readability/understandability (and to match the new pattern throughout the app with Nav) we should probably add a heading to this screen, in either the header or in-line on the page:
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/74d6ba4d-67ec-47ff-b8dd-a5b93ff30161)

## Steps to Reproduce

_Will need the 3/16 mid-day build or later, to see this in its best format_

Step 0A: If you've logged in before, you can reset to first time login with an option on the developer screen (Profile > Settings > Developer Screen > reset to first time login)

Step 0B: Otherwise, install the app

Step 1: From the initial screen of the app, tap "sign in" to be brought to the screen in question (screenshot above)

## Desired behavior

priority 1 (directly addresses the bug): According to the spreadsheet, the screen should be called "Sign in" and that title lives in the body of the screen (keep the current screen type & transition). I'd leave the back label as-is for now just because we're going to change the screentype anyway.

priority 2 (not the bug, but closely related): In addition to the title change above, the screen type changes to a fullscreen subtask & the back action changes to "Close" instead of "Back"

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Issue Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-tracking) for details on Severity Levels

- 3 - Low

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, feature, bug)
- [ ] Estimate of 1 added

**Comment by theodur** [comment] 2023-09-08 05:19
It turns out this screen was already using the fullscreen subtask template, it just needed the title and label updated. Here's what it looks like with the changes:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamw5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f24f06889c04192381a8a9c11c24650b984ffd1e/image.png)

@htcollier Could you confirm that this looks right?

**Comment by htcollier** [comment] 2023-09-08 14:35
The screen type, title & back action look great - thanks @theodur.

**Comment by DJUltraTom** [comment] 2023-09-19 22:30
Verified this is looking as designed in the screenshots

**Comment by DJUltraTom** [comment] 2023-09-22 21:38
verified this is appearing as expected on the Latest QA Dev build. closing as deployed

**Closed by DJUltraTom** 2023-09-22 21:38 UTC
Labels: sev-3, bug, front-end, Closed - Deployed/Fixed, IA & navigation, mobile-blue-team, scrubbed, Post Planning Add
