### ISSUE TITLE
QA Counting Logic for Each Home Screen Feature 

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7533] opened 2023-12-13 21:57 UTC
Background:
* This ticket covers QA'ing the counting logic for each of the home screen features

AC:
- Confirm the counting logic for each feature, in this  [document](https://docs.google.com/document/d/1D4TJk3l_lM0IrPqfU-6SgES3ohGdboOxo7SgMLyqIlU/edit)

**Comment by TKDickson** [comment] 2024-01-08 15:15
Moving to blocked as there's a discussion (scheduled for next sprint tentatively) about potentially changing the claims count logic FYI @ajsarkar28 on the ticket move

**Comment by TKDickson** [comment] 2024-01-16 17:49
And moving back to blocked; the count is being returned correctly from the backend for Rx but we're not yet using it on the frontend.

**Comment by TKDickson** [comment] 2024-01-19 15:28
This ticket is easy to split in a way that makes it more likely to get worked on (less likely to be blocked, easier to complete smaller segments in one go). Going to do that, then close this one

**Comment by TKDickson** [comment] 2024-01-19 15:34
Closing this as a duplicate of the four tickets above - 7757, 7758, 7759, and 7760

**Closed by TKDickson** 2024-01-19 15:34 UTC
Labels: blocked, qa, global
