### ISSUE TITLE
BUG - [Sev 3] Video Visit appointments not showing on web, but shows on mobile (GFE & At Home)

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6686] opened 2023-09-11 16:46 UTC
## What happened?

While pulling some documentation together from appt content audit, I noticed a potential bug that may be in production.   

Wanted to double check if it is staging data issue or not before spinning up a ticket.

There is a Video appt-home appt for 10/2 at 10:00 a.m. EDT that is showing up on mobile, but does not show up on web appt list. 

Test user: alfred.castillo@id.me
PW; same as Judy

## Acceptance Criteria:

1) Validate if this is a mobile issue of showing the additional appt or is this an issue on web of not displaying.  

Screenshots attached

[Web Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEdJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8ce62bc5281beefd9c04028f2f1bcb261819bc16/Screenshot%202023-09-11%20at%2011.57.43%20AM.png)

[Mobile Screenshot](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFdJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--741c52763b896acd24d0de4e076db044f52d9610/IMG_8081.PNG)

**Comment by MekoHong** [comment] 2023-09-11 16:47
Issue added; Jason has some bandwidth to research, pulled in for sprint to review

**Comment by Tonksthebear** [comment] 2023-09-12 11:42
The issue appears to not be related to backend or web.

`VAOS::V2::AppointmentsService` has a parameter `start_date` which gets forwarded on to `vaos` upstream appointments URL as parameter presumably intended to be used as a starting point for which appointments to fetch in which date range. 

Due to how the mobile view works, mobile automatically sets this start_date to the first day of the previous year. Web, however, does not need as large of a range, so they use the first day of the previous month. The appointment in question is in the FUTURE, so one would thing neither of these start dates should cause any difference in the appointment showing up. However, the web's start date removes the appointment from the list. When adjusting their start date to the same as mobile's, the appointment reappears. 

For this reason, we believe the filtering logic from VAOS's upstream endpoint is using incorrect data for determining which appointments should be visible based on the start date. Perhaps they're using a created_on field, or some other date not related to the actual appointment date. Regardless, this appears to be an issue for another team.

**Comment by MekoHong** [comment] 2023-09-12 17:44
Update from Marcy: The appointments on 9/25/ and 10/2 are staging anomalies.  Those clinics are not in Mock CDW - MFS in staging.  So this explains why those two appointments do NOT display in VAOS web.  This does not appear to be a bug

**Comment by MekoHong** [comment] 2023-09-12 17:49
@Tonksthebear can you have a peak at 2 additional appts for this user on 9/18 there is a Mental health appt at 8:00 a.m and canceled mental health appt at 11:30 am that are showing on the web, but are not showing on mobile.  Can you check to see why?  screen shot attached
<img width="743" alt="Screenshot 2023-09-12 at 1 47 03 PM" src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/90273080/5daeb69a-7fbc-475c-a161-9dea72abb96d">

**Comment by Tonksthebear** [comment] 2023-09-12 22:45
@MekoHong After a few hours of more frustrating thread pulling it's the exact same issue. The wider window mobile uses makes those disappear, while the smaller window makes them appear. I suppose if their previous answer is correct, this is just more staging weirdness

**Comment by Tonksthebear** [comment] 2023-09-19 16:03
Had a meeting with VAOS and they're looking into data I sent them

**Comment by bischoffa** [comment] 2023-10-05 13:42
@Tonksthebear any updates from the VAOS team from your past meeting with them?

**Comment by MekoHong** [comment] 2023-10-05 14:16
@bischoffa I don't believe we have, @Tonksthebear I'll follow up in the thread

**Comment by TKDickson** [comment] 2023-10-12 20:41
Note from bug scrub this sprint: Not scrubbing this one (yet); likely in the not a bug/staging data category from the investigation thus far

**Comment by MekoHong** [comment] 2023-10-13 14:05
Yes, this is ongoing investigation with the appointments team.  They made some fix on their end, but I am still seeing some mismatch on appt list display.  I have on my to do to follow up with them and share the examples of the mismatch.  Here is the thread for reference https://dsva.slack.com/archives/CMNQT72LX/p1695058886997429

**Comment by TKDickson** [comment] 2023-10-18 19:08
Just a note - Potentially related to #5809, the open VAOS ticket in the DSVA slack mentioned above does include an example of "telehealth in web & in-person in app" discrepancy.

**Comment by jperk51** [comment] 2023-10-19 15:27
@TKDickson @MekoHong @Tonksthebear Is there any follow up investigation we want the mobile BE engineers to pursue from this ticket? We've got capacity in the coming sprint if there's anything here that makes sense for us.

**Comment by MekoHong** [comment] 2023-10-19 16:14
@jperk51 the only follow up from our side Paul asked for the appt Id's for the example mismatches that I provided the team and @Tonksthebear was going to work to provide those over.  For the most part I believe the investigation is with the appointments team to troubleshoot further.  Adding the PDF/Google slide I shared with them here.  For reference.  https://docs.google.com/presentation/d/14ysg4FtBspzvvd4yM_Ff-RqUt5zNSO1wJRuFQgjw3iU/edit?usp=sharing cc: @bischoffa

**Comment by Tonksthebear** [comment] 2023-10-20 16:50
@MekoHong the team created an incident report and seemed to be investigating on their own so I didn't think they cared about the appointment ids. Am I wrong there? I'm happy to pull the ids and provide them to that slack thread if it's valuable to them

**Comment by Sparowhawk** [comment] 2024-05-23 16:04
@bischoffa @TKDickson Is this still an issue or can we close this one?

**Comment by TKDickson** [comment] 2024-05-23 16:09
No idea. I haven't been involved in follow-up since October when I attempted initial bug ticket scrubbing.

IDK how likely it is that this got transitioned to @ala-yna - if neither she nor @bischoffa know, then I'd recommend trying to reproduce with staging users with a high number of appointments (either FE, or could go in @rbontrager backlog) instead of closing right away.

**Comment by bischoffa** [comment] 2024-05-23 16:14
From what I recall this was still an issue when Meko left thus tagged Health back in Nov. I think the intent was to look into it when Video Visits was prioritized in Health (after phone / in person). However given time has passed not sure if its still an issue. 

I would align with @TKDickson above about retesting it to see. Likely the code we tested then is no longer the same code we have now.

**Comment by jperk51** [comment] 2024-07-01 17:10
Is this still happening?

**Comment by ala-yna** [comment] 2024-07-24 13:43
Talked this over with @rbontrager  - this issue appears to be resolved. Closing this out.

**Closed by ala-yna** 2024-07-24 13:43 UTC
Labels: sev-3, bug, Health, appointments, scrubbed, API team
