### ISSUE TITLE
BUG - sev-2 - Android - duplicated appointment UI entries

### ISSUE THREAD

**Issue by RIAEvangelist** [department-of-veterans-affairs/va-mobile-app#8174] opened 2024-03-12 18:50 UTC
## What happened?
Navigate to appointments screen, all appointments are duplicated one time. This means they each show twice.

## Specs:

- Device: pixel 7 pro
- OS: Android 14

## Steps to Reproduce
Login, navigate to medical, navigate to appointments, be confused because all of your appointments are duplicated.

## Desired behavior
Should only see one entry per appointment.

## Acceptance Criteria
No duplicated appointments

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
Will confuse most users to the point they have to call in to make sure they are not double booked.
 
Sev-2

- Impact: Low 
- Frequency: High

Sev- 2 

## Linked to Story
N/A

## Screen shot(s) and additional information
![Screenshot_20240312-112957.png](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/369041/905bdc90-e59d-4196-bc74-dea502a469c0)

![Screenshot_20240312-112949.png](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/369041/441b8251-6a3a-4cb6-b717-16b9f304b46e)

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment] 2024-04-25 16:58
@rbontrager @TKDickson If this was an app code issue I am certain it was fixed when the appointments react query migration got merged a few days ago. Our old redux slice code had a lot of manipulated fields that are just not used anymore and is now strictly what the api sends us. So if this persists as an issue after RQ gets released then it is likely a BE or upstream issue.

Not sure if we want to leave this open for investigation or close this for now and re open if needed.

**Comment by bischoffa** [comment] 2024-04-30 16:00
Sev-2 label missing so was added in

**Comment by RIAEvangelist** [comment] 2024-04-30 17:57
Confirmed fixed.

**Closed** 2024-04-30 17:57 UTC
Labels: sev-2, bug, Health, appointments

**Comment by bischoffa** [comment] 2024-05-01 12:40
In conversation with H&B team, this seemed to be caused by VA Notify team. H&B team considering this closed as well based on RIA's confirmation.
