### ISSUE TITLE
CU - Change many components out of 'link' and 'button' roles

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9464] opened 2024-08-26 21:19 UTC
## Proposed Change

In response to  #9288 (in order to stop the worst impacts), we changed the role for several components to either 'button' or 'link'. Some of them can stay that way (bottom navigation bar, menu list items) but [all of the remaining changes](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9457) should eventually be changed back to a role that 1) is correct and 2) continues to work with all assistive tech.

This could be in response to a fix from iOS or React Native, or could be if we find a working medium-term solution with #9463.

## Checklist
- [x] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by alexandec** [comment] 2024-09-23 15:02
As described in [#9474](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9474), the relevant keyboard navigation issue was fixed by Apple in iOS 18 as of 9/16/24. Once enough of our users have upgraded to iOS 18, we can implement the changes described in this ticket.

I've created a branch called `revert-keyboard-nav-workarounds` that mostly reverts the changes as desired. However the bottom navigation bar and menu list item changes should not be reverted, so a couple tweaks to the branch will be required.

**Comment by TKDickson** [comment] 2024-09-25 18:28
This is global work & will build off of Chris's existing investigation, but we'll be the ones doing it; removing his assignment & the health label - FYI @ala-yna

**Comment by rbontrager** [comment] 2024-10-29 18:12
@cadibemma VoiceOver is not saying the role for any of the changes you made on iOS. So for example:
- Segmented controls (using claims history active/closed): Saying "Active 1 of 2. Review you..." its saying "Active 1 of 2. tab. Review your..."
- Radio button (using gender identity): "Man" instead of "Man radio button"
- VAModalPicker (payments): "Select a year picker. Filled 2017" instead of "Select a year picker. Filled 2017 spin button"

**Comment by dumathane** [comment] 2024-11-04 18:19
@rbontrager CC: @cadibemma ,

Rachael, do you know/can you test if this was working on a previous ios and is now broken in 18? Do you have some older ones we could load Chika's branch on?

Thanks, let us know.

**Comment by rbontrager** [comment] 2024-11-15 12:05
Determined that the above issue was actually an issue before 9288 and out of scope.  Made bug ticket [10185](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9889/files) to address it.  Otherwise verified over voiceOver that segmentedControls, VAModelPickers, and Radio groups correctly read out as tab, spinbutton, and radio roles for android respectively and still function as intended. Approved by QA.

**Closed by rbontrager** 2024-11-15 12:05 UTC
Labels: front-end, accessibility, code upkeep, global, QA 2
