### ISSUE TITLE
Investigation - Messaging Reply Triage Team Errors

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#6822] opened 2023-09-25 16:29 UTC
[Sentry Error](http://sentry.vfs.va.gov/organizations/vsp/issues/41780/?environment=production&project=3&query=is%3Aunresolved+mobile&statsPeriod=30d)

ACs:
- [ ] Determine if these errors are expected or not
- [ ] if so, try to figure out a way we could possible mitigate them or preemptively stop the user from take the erroring action
- [ ] if not, determine what's causing the unexpected error and put together the necessary tickets for the fix

Timebox this to 3 pts.

**Comment by aherzberg** [comment] 2023-10-12 21:37
It looks like this is not a transient issue (see logs here: https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20%40http.url_details.path%3A%22%2Fmobile%2Fv0%2Fmessaging%2Fhealth%2Fmessages%2F4924574467%2Freply%22%20&cols=host%2Cservice&event=AgAAAYsltCMFTpz6YQAAAAAAAAAYAAAAAEFZc2x0Q2JwQUFBcHBVZXRaYy1ZVmdBcgAAACQAAAAAMDE4YjI1YmYtYWEwNS00ZGFkLTk3MjUtMjQ1Zjg1MTA3Mjcy&index=%2A&messageDisplay=inline&refresh_mode=sliding&saved-view-id=1184&stream_sort=desc&viz=stream&from_ts=1695848709039&to_ts=1697144709039&live=true). A single user tried the same endpoint multiple times over 2 days and still got the same response. 

I also see this issue with both `client.post_create_message_reply` and `client.post_create_message_reply_with_attachment`. So doesn't seem to be a formatting issue switching between the two. 

The only other string I can think to pull is comparing the body parameters to successful requests to see if there's anything missing but the body parameter is being filtered, see conversation: https://adhoc.slack.com/archives/C039MQU32E8/p1697145735039599

**Comment by aherzberg** [comment] 2023-10-13 20:00
context on when that error appears: https://dsva.slack.com/archives/C05TU9FPZU0/p1697213684810449
Also noticed that on our docs that if a message is older than 120 days then its considered expired. checking to make sure FE checks that. so don't seem to have a status field like that

**Comment by aherzberg** [comment] 2023-10-13 22:14
I see a `get_triage_teams` endpoint in the SM client. I'll confirm with MHV team but we may need to manually check if the message triage team is a associated with the user.

**Comment by jperk51** [comment] 2023-10-16 14:59
Asking a few follow up questions to MHV about how they handle this situation on their site

**Comment by aherzberg** [comment] 2023-10-16 16:55
Confirmed we can use the triage team endpoint to determine before hand if we'd get this message. Need FE and Product to determine how we want to handle this. Assigning to Jayson.

**Comment by jperk51** [comment] 2023-10-16 17:45
Currently, as of an update a month ago, we do what MHV does. Which is allow the user to send the reply and then show them a specific error message letting them know they are no longer associated with the triage team so the message didn't go through. 

That being said, we **should** use the `get_triage_teams` endpoint to hide the reply button on message we know we would get this error on. We could also use it to preemptively show a message letting the user know what's going on. This will dramatically decrease the number of unnecessary calls to our and MHV's API 

@bischoffa

**Comment by bischoffa** [comment] 2023-10-17 13:47
@jperk51 can you share any estimates / data on the number of calls this would decrease?

**Comment by jperk51** [comment] 2023-10-17 16:12
Our sentry logs indicate about 9.2k in the last 30 days. 3.3k different users.

**Comment by bischoffa** [comment] 2023-10-18 17:45
Created this ticket [7037](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7037) for the remediation. Going to review it with Jen to get UX's perspective on how to incorporate the message. Then intent is to meet with FE / BE for sizing efforts to go @jperk51 suggested resolution.

**Closed** 2023-10-23 14:22 UTC
Labels: back-end
