### ISSUE TITLE
Component App Propagation - Alert

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6854] opened 2023-09-27 13:37 UTC
## Description

This ticket needs to be sprint-aligned with the Global App team to be able to offer support, collect feedback, and make needed changes to the component package for App Propagation. Due to the nature of this ticket, the work will likely carry over multiple sprints.

## Important links

- [npm package](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library)

## Definition of Done

- [ ] The Mobile app team has been alert to the existence of the new component
- [ ] Areas of the the app that need to be updated have been communicated and documented (35 at the time of this ticket)
   - [ ] Explore shifting the Cerner Alert over to using the Alert Box component as well
- [ ] The new alert box component is implemented in all areas of the app
- [ ] The Mobile apps have been released to their respective app stores with the component installed

**Comment by theodur** [comment] 2024-07-09 23:37
Closing this since it's a duplicate of https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8468. Or technically that ticket is a duplicate of this one, but that one is more recent with added details

**Closed by theodur** 2024-07-09 23:37 UTC
Labels: front-end, mobile-platform, global
