### ISSUE TITLE
Update Health Screen with Cerner Alert

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#8134] opened 2024-03-07 18:57 UTC
AC:
- Health screen displays text describing that some VA facilities use Cerner, which includes a link to the Cerner facilities alert
- If a Veteran is a Cerner only user, then the alert is always displayed once every session, which is the first time they go the Health screen
- If a Veteran is a Cerner and VA Health user (mixed patient), then the alert is displayed the first time they ever go to the Health screen

Designs should reflect this [Figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3264-2449&mode=design&t=YiXDDHgDNT7ZeNAC-4)

**Comment by TKDickson** [comment] 2024-03-08 14:59
[Test case link](https://dsvavsp.testrail.io/index.php?/cases/view/63199&group_by=cases:section_id&group_order=desc&display_deleted_cases=0&group_id=13520)

**Comment by TKDickson** [comment] 2024-03-08 15:04
I will also note that - when testing this ticket - I want to check what happens when someone who has previously seen the health screen Cerner panel as one type (ex: cerner only) switches to the other type (cerner mixed), in both directions.

**Comment by TKDickson** [comment] 2024-04-23 16:28
First flow I tried didn't work: a cerner-only user (ssoissoetesting+mhvcss4@gmail.com) got the right content in the popup, but the large panel only showed automatically the first login. When I forcequit the app and used biometrics to log in again, the panel didn’t appear. I let Chika know/she's going to look into it, while I continue to test to see what else I uncover.

**Comment by TKDickson** [comment] 2024-04-23 17:29
Found #8455 (not caused by this work) while testing.

**Comment by TKDickson** [comment] 2024-04-25 19:19
_Note to self: I want to make sure I check demo mode_

**Comment by TKDickson** [comment] 2024-04-25 20:08
Found #8477 while testing this branch. I don't know if it's caused by these changes, but I'd rather hold back on merging this until we're more sure/have more info, for now.

**Comment by TKDickson** [comment] 2024-04-29 16:33
_Note to self: also need to check how availability framework interacts with this, particularly "auto-popup" + waygate_

**Comment by TKDickson** [comment] 2024-04-29 17:20
<img width="373" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmlmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--740c1f0ad665fb4a577cce8f4aa105df480ffcc1/image.png" alt="image.png" />
Doesn't meet contrast in dark mode

**Comment by TKDickson** [comment] 2024-04-30 14:39
* Should update demo mode for consistency (currently showing the "all cerner" alert on health category screen, but not the Cerner disclaimer on home) -- I think the ideal state here would be to show the cerner disclaimer on home AND the 'some Cerner' on health.
* Need to set a max size for the link component icon (same as the rest of the HSP icons)
* Showing the bullet points as incorrectly actionable with voice control

<img width="373" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzJrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a05c0f7f121eb93e7e9441b1bfcfbbfe4499004/image.png" alt="image.png" />

<img width="373" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3VrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27aa06002b3842a23a286dae1b643bcd8cc3f374/image.png" alt="image.png" />

**Comment by TKDickson** [comment] 2024-04-30 14:49
Availability Framework version 1 (DenyAccess) is just a little broken (which is better than I was expecting!). It's correctly displaying, instead of the auto-popup. However, it's being displayed twice on auto popup (and correctly just once when you tap the 'check if I've got Cerner facilites link'). So ultimately [the user has to OK two popups to get to the health screen.](https://drive.google.com/file/d/1mFldgWS5xNCRn7c8JNYYKf7UUQleYP4Q/view?usp=sharing)

**Comment by TKDickson** [comment] 2024-04-30 14:49
Sending back to @cadibemma for these four things.

**Comment by TKDickson** [comment] 2024-05-03 14:18
@cadibemma Demo mode issue is still present. I can test the other stuff because it's isolated, can you please fix that?

**Comment by TKDickson** [comment] 2024-05-03 14:27
Never mind - that demo mode thing is indicative of an actual bug, and it's not caused by this branch. Wrote up #8532 for that problem

**Comment by TKDickson** [comment] 2024-05-03 16:07
Holly OK'd a non-MVP fix for #8534, caused by this branch/found during this testing

**Comment by TKDickson** [comment] 2024-05-03 16:08
The bullet points thing is a pre-existing/known/larger issue - #8509.

**Comment by TKDickson** [comment] 2024-05-03 16:26
Icon size is now capped, and AF1 use case issue I outlined above is resolved (I'm only seeing the popup once).

I ran into a thing where if we're setting AF on the Health Screen itself, we can run into strange interactions with the Health Help autopopup, which I'm asking Holly about in Slack.

Essentially:
In an extremely specific (use case 2) Availability Framework setup:
We are allowing people to GO to the health screen, but not showing any content on the Health screen (AF2, again)
They are a Cerner person who meet the usual Cerner logic
A veteran would [see the Cerner popup when navigating to Health, but…. not be able to actually open the Cerner popup themselves on the page (or see any other Health content).](https://drive.google.com/file/d/11Pq65e2fpMqoXHottqNWG1l1N1YHbVKS/view?usp=sharing)
It’s not possible to build around this with AF - denying access to the Cerner popup PLUS the situation above would lead to a UI something [like this. ](https://drive.google.com/file/d/12CvlfCGIXweropb3qtckpgn_llkpXvRO/view?usp=sharing)

**Comment by TKDickson** [comment] 2024-05-03 17:00
Decision from Holly: We should check for AF use case 2 before displaying the Health Help cerner auto-popup. Sending back for changes.

**Comment by cadibemma** [comment] 2024-05-03 18:55
Fixed footer text alignment & AF use case 2

**Comment by TKDickson** [comment] 2024-05-06 14:48
Was distracted by AF use case 1 on health screen (#8548) but confirmed that's happening on develop as well.

The AF2 case outlined above, as well as alignment, are fixed.

**Comment by TKDickson** [comment] 2024-05-06 14:49
Merged, closing

**Closed by TKDickson** 2024-05-06 14:49 UTC
Labels: QA, front-end, personalization, global
