### ISSUE TITLE
Implement Deep Linking: Appointments 

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6665] opened 2023-09-07 14:49 UTC
## Description

**Background:** Deep links are a type of link that send users directly to an app instead of a website or a store. They are used to send users straight to specific in-app locations, saving users the time and energy locating a particular page themselves – significantly improving the user experience. **_Note: The MVP for Deep linking was specific to secure messaging- Reference_**[ HERE](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6342)

As part of this story we want to Implement Deep Linking for **APPOINTMENTS** utilizing a custom URL via **EXISTING** push notifications in the Mobile app.

**User Story**

**As a mobile app user, I want to quickly access the appointment details page from a push notification, so I can view important information pertaining to that upcoming appointment**

**This Story also Includes:**

- **Back Navigation**: As a mobile app user, after I have navigated to the appointment (via the deep link), I would like to exit and be taken to the Upcoming Appointments page

## Acceptance Criteria
  

-  [ ] Deep Link and navigate the user to the specific upcoming appointment (**Specific Message ID**). Ex: User receives a push notification and this will “deep link’ to the specific appointment within the upcoming appointments.
**Note: Existing Push Notifications Only**
-  [ ] Back Navigation: As user exits the appointment, they will be taken back to correct Screen (**See Example above)**
-  [ ] Note any risks and potential blockers

**Comment by StacyB2023** [comment] 2023-10-04 14:54
@theodur @dumathane As this one is already estimated, do we need a separate spike ticket moving into sprint 82? Or would we like to work off this already estimated ticket?

**Comment by theodur** [comment] 2023-10-23 21:37
The data being sent with appointment notifications from VEText includes the clinic ien and appointment date/time. The appointments that are fetched from our mobile backend (which ultimately come from VAOS) don't include the clinic ien, so we don't currently have a way of mapping appointments from VEText notifications to the appointments in the mobile app, as the date/time of the appointment alone isn't enough to uniquely identity the appointment. ([Slack thread](https://dsva.slack.com/archives/C01CSM3EZGT/p1697744361996109))

The appointment ien is something that can can be used instead of the clinic ien to map appointments on the FE. Our BE team was waiting on VAOS to make the appointment ien available from the upstream service, but that was recently made available. The next things that need to happen in order for us to be able to map the appointments on the FE is:
- Our BE team needs to update the logic for our appointments API accordingly
- VEText needs to update the appointments push notification template to include the appointment ien instead of the clinic ien in the data that's returned from the notifications

As of now, this ticket is blocked by those two tasks, primarily the appointments API needing to be updated. BE is going to spin up a ticket for that work for this upcoming sprint. Once the ticket is made, this one will be marked as blocked by it.

Also for reference, I have a draft PR up for the work for this: https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7030. That worked was done with the assumption that appointment IDs would be able to be sent with appointment push notifications, but since appointment IDs are from VAOS, VEText doesn't have anyway of knowing the IDs, since they are different systems. The PR will need to updated to reflect the new data being passed from the appointment notifications when work on this is resumed

**Comment by jperk51** [comment] 2023-10-24 17:26
Blocked while I work with Shane to figure out if what fields we need to us to uniquely id appts (both VA and CC). Details on why apptIEN is not gonna work are [here](https://dsva.slack.com/archives/C023EFZPX4K/p1698157235719349)

**Comment by StacyB2023** [comment] 2023-10-30 16:01
@theodur would this still be considered blocked? I think we removed the appts API blocker? cc: @jperk51

**Comment by jperk51** [comment] 2023-10-30 16:03
This is blocked by the API work. Putting up the PR now

**Comment by jperk51** [comment] 2023-11-01 16:57
The vetext_id field should have data now in staging @theodur

**Comment by theodur** [comment] 2023-11-02 18:37
I updated my PR to use the vetextId and everything is working well in staging when testing with the VEText team. The PR is open and ready for review from FE

**Comment by theodur** [comment] 2023-11-03 01:10
After doing some extra testing, I noticed Android wasn't handling the url from the appointment notification payload correctly. This was due to the semicolon(`;`) that's in the vetextID, e.g. `vamobile://appointments/442;3231115.0`. VEText said they can encode the semicolon in the URL so that Android can handle opening the link. I already made changes on the FE to decode it, so we're there. The VEText team will update the notification template, most likely tomorrow. It should be a relatively quick change. No change to our API are needed

**Comment by TKDickson** [comment] 2023-11-07 14:23
This is being tested by the VEText team and @theodur, so Theo feel free to merge when you all are finished.

**Comment by TKDickson** [comment] 2023-11-07 19:39
Did some regression-testing around appointment details, which is looking solid. Found #7225, not caused by this change.

**Comment by TKDickson** [comment] 2023-11-07 19:45
No further testing needed in develop, closing

**Closed by TKDickson** 2023-11-07 19:45 UTC
Labels: front-end
