### ISSUE TITLE
Bug: - Sev 3 - All(?) - "Refill in process" showing when data says, "unknown"

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#5985] opened 2023-06-09 13:32 UTC
## What happened?

A report from Sirisha Yeruva that there appears to be a mismatch between what the MHV database is for a prescription status and what is being displayed in the app.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

Attaching a screenshot of the database showing an "unknown" status and the app showing "in process"

![unnamed.png](https://images.zenhubusercontent.com/5f9c54a1ad5a556830833cd6/59567d31-b424-44c7-b232-422aa7fa983e)

![unnamed-1.png](https://images.zenhubusercontent.com/5f9c54a1ad5a556830833cd6/7e1b9721-369b-4dd3-89c3-acf62f4accc5)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment] 2023-08-11 17:48
converted this ticket template to bug ticket template.

**Comment by bischoffa** [comment] 2023-08-11 17:48
Ask here would be to do some investigation to see if we see mismatches.

**Comment by Sparowhawk** [comment] 2023-10-10 23:00
@bischoffa Looking back over the code there is no way a unknown prescription sent to us correctly could be displayed as refill in progress:

    Here is the code that is used for that determination:

switch (status) {
    case RefillStatusConstants.ACTIVE:
      return t('prescription.history.tag.active')
    case RefillStatusConstants.DISCONTINUED:
    case RefillStatusConstants.DISCONTINUED_BY_PROVIDER:
    case RefillStatusConstants.DISCONTINUED_EDIT:
      return t('prescription.history.tag.discontinued')
    case RefillStatusConstants.EXPIRED:
      return t('prescription.history.tag.expired')
    case RefillStatusConstants.HOLD:
    case RefillStatusConstants.PROVIDER_HOLD:
      return t('prescription.history.tag.active.hold')
    case RefillStatusConstants.ACTIVE_PARKED:
      return t('prescription.history.tag.active.parked')
    case RefillStatusConstants.REFILL_IN_PROCESS:
      return t('prescription.history.tag.active.inProgress')
    case RefillStatusConstants.TRANSFERRED:
      return t('prescription.history.tag.transferred')
    case RefillStatusConstants.SUBMITTED:
      return t('prescription.history.tag.submitted')
    case RefillStatusConstants.DELETED:
    case RefillStatusConstants.UNKNOWN:
      return t('prescription.history.tag.unknown')
  }

The only thing I can think of is potentially a caching or status updated and it didn't make it to mobile just yet. I am confident the issue is upstream and there is nothing we can do.

**Comment by bischoffa** [comment] 2023-10-11 12:11
Is there anyway to capture what the issue is and who upstream its coming from so we can communicate with the necessary upstream system?

**Comment by Sparowhawk** [comment] 2023-10-13 14:24
@bischoffa No there is not any way for us to log if web is showing us something different that what mobile is. We are just displaying what the api is returning to us, which we assume is correct. There isn't any mismatching on mobile end that we could capture.

**Comment by bischoffa** [comment] 2023-10-13 14:28
Thanks @Sparowhawk 

@timwright12 based on information above I am not sure the next steps we can do to identify or even communicate the error with an upstream team. Given this I will be closing the ticket. If you want it re-opened please comment what the next steps are.

**Closed by bischoffa** 2023-10-13 14:28 UTC
Labels: sev-3, bug, qa, front-end, rx-refill, scrubbed
