### ISSUE TITLE
Implement & Test SSO

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#9286] opened 2024-08-07 17:20 UTC
AC:

- Update mobile sign-in to request the new device_sso scope, securely store the returned device_secret, and pass the secret back when revoking the session.
- Add a feature-flagged web view (ex. no appointments screen) containing a logged-in va.gov page to demo the mobile SSO capability. 
  - LINK_URL_SCHEDULE_APPOINTMENTS=https://www.va.gov/health-care/schedule-view-va-appointments/

[Identity SSO Token documentation ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/Authentication%20Types/Client%20Auth%20(User)/auth_flows/device_sso_token_exchange.md)

**Comment by TKDickson** [comment] 2024-08-07 17:25
Testing notes:
* QA should make sure to test all supported credentials (MHV, DS Logon, etc)
* During logout of the mobile app, user will *not* be logged out of any website sessions they've opened. Timeout/logout of the web session will continue to be its own thing/not triggered by anything that happens in the mobile app.

**Comment by theodur** [comment] 2024-08-20 05:02
While working on this, I noticed there will need to be some changes in the `vets-website` repo for this to work. The first part of the SSO process entails passing the `scope=device_sso` parameter to the `sign_in/authorize` endpoint. The problem is the mobile app doesn't directly call the `sign_in/authorize` endpoint, that happens in the login webpage when the user selects their login method. This means the actual API call to the `sign_in/authorize` endpoint and its parameters are out of our control, and is managed by the code in `vets-website`. 

The way the parameters get passed to the `sign_in/authorize` endpoint is through what we pass to the login screen when the user taps the `Sign in` button in the app; then the code from `vets-website` parses those parameters and sends them along when it makes the request to `sign_in/authorize`. When I looked through the latest version of the authentication logic in the `vets-website` repo, I noticed they haven't updated the [parameters](https://github.com/department-of-veterans-affairs/vets-website/blob/2d6a4d92d9fab7fe1ef7eacaca6101df51ac9ad4/src/platform/user/authentication/constants.js#L155-L163) that they're parsing and passing to the `sign_in/authorize` request to include `scope`. So even when we pass the `scope=device_sso` on our end, it's not being picked up on the webpage.

I have a [draft PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9412) up with a draft implementation that should work, I just can't test it as of now without the `vets-website` code being updated. I'll speak more on this in stand up tomorrow.

**Comment by theodur** [comment] 2024-08-20 19:46
I reached out to the identity team, and they're going to make a ticket for parsing the `scope` parameter on the sing-in page. I'm moving this ticket to blocked for now

**Comment by theodur** [comment] 2024-09-09 18:28
The identity team was able to add logic to handle the `scope` parameter was added to the sign-in page. Now the `device_sso` scope is being passed to the authentication API call and I'm able to receieve the SSO cookies. I was able to confirm the SSO session is being properly set in the Webview now. I confirmed this by visiting https://staging-api.va.gov/v0/user in the Webview and recieved data about the authenticated user that wouldn't be available if the user wasn't authenticated.

The issue I'm running into is regardless of which page I visit on the website that requires a user to be signed in, it redirects the Webview back to the sign in page. So even though API requests are recognizing the SSO session, the actual website doesn't recognize the user being logged in. SSO won't work as intended until the website is updated to recognize the SSO cookies and bypass manual sign in. I reached out to the identity team in the [Slack thread](https://dsva.slack.com/archives/C04LFGY2SJK/p1725900393898079?thread_ts=1724179641.025989&cid=C04LFGY2SJK) where prior conversations tooks place, so hopefully that can be addressed soon, but as of now this ticket is externally blocked.

**Comment by theodur** [comment] 2024-09-09 22:06
After syncing with the identity team, it turned out all we had to do was set the `hasSession` field in local storage to `true`. Now SSO seems to be working flawlessly. I'm going to leave the testing changes in my draft PR up for demo tomorrow, and then after that, I'll revert the testing changes, and open my PR for review

**Comment by TKDickson** [comment] 2024-09-17 20:38
Blocked awaiting test plan/test plan review completion. Added the blocking ticket as a dependency

**Comment by TKDickson** [comment] 2024-09-19 15:49
Unblocked, removing label. Starting [testing](https://dsvavsp.testrail.io/index.php?/runs/view/5948&group_by=cases:section_id&group_id=24129&group_order=asc) today.

**Comment by TKDickson** [comment] 2024-09-20 18:01
If a user stays logged into the app longer than 5 minutes (aka would need to refresh one of their tokens), the app will successfully do so. However, opening an SSO-enabled webview after that point will NOT log you in. Here's the series of endpoints that fail, and their returns. Each of these APIs is called twice, I'm assuming that's an automatic-website-retry thing.

staging-api.va.gov /v0/user
```
{
	"errors": "Access token has expired"
}
```

then staging-api.va.gov /v0/sign_in/refreshnull
```
{
	"errors": [{
		"title": "Not found",
		"detail": "There are no routes matching your request: v0/sign_in/refreshnull",
		"code": "411",
		"status": "404"
	}]
}
```

and then the v/0/user endpoint fails twice again.

**Comment by theodur** [comment] 2024-09-24 04:02
@TKDickson Should be fixed now ✅ sending back your way

**Comment by TKDickson** [comment] 2024-09-24 20:31
Things found during today's testing:
- The accessibility hint/help text for the link "this page will open in your device's browser" is *not* true when SSO is on, but I don't think we should be messing with the accessibility text via feature flag. Not sure what to do with this one.
- iOS handles loss of internet better than Android (iOS will load the webview logged in after loss of internet; Android will load it logged out so you have to close and reopen the webview for the SSO to work after loss of internet)
- If you have the webview open (when the access token expires/5 minutes), both platforms exhibit the same behavior. You are 'still logged in' on the page that's showing, you are logged out on the *next* page you navigate to, then you're logged back in again on the next page after that. Or if you close and reopen the webview, you're correctly logged in. Seems more like a future enhancement-y type of thing to address (presumably on the web side?)

**Comment by theodur** [comment] 2024-09-24 20:53
@TKDickson 
> The accessibility hint/help text for the link "this page will open in your device's browser" is not true when SSO is on, but I don't think we should be messing with the accessibility text via feature flag. Not sure what to do with this one.

This has to do with how the links are launched by the app. When we launch a link via WebView, we're technically not opening the user's device browser, they're still in the app, it's just that they're in a WebView screen that shows the webpage, so the app isn't programmed to show the alert for "this page will open in your device's browser" for WebViews. This is the case for existing WebViews in the app as well.

> iOS handles loss of internet better than Android (iOS will load the webview logged in after loss of internet; Android will load it logged out so you have to close and reopen the webview for the SSO to work after loss of internet)

When you say loss of internet, do you mean turning the Wi-Fi off on the device after navigating to the WebView?

> If you have the webview open (when the access token expires/5 minutes), both platforms exhibit the same behavior. You are 'still logged in' on the page that's showing, you are logged out on the next page you navigate to, then you're logged back in again on the next page after that. Or if you close and reopen the webview, you're correctly logged in. Seems more like a future enhancement-y type of thing to address (presumably on the web side?)

This one is interesting, because I'd expect if the website logs the user out after 5 minutes, that subsequent pages shouldn't load, but it sounds like they do load just intermittently? There may be something we could do to address this, like adding logic that tracks when the token expires, and if the user navigates to another page when the token is expired, it would refetches the cookies again. I agree this would be more of a future enhancement type of thing, especially since the website will let the user know that their session is going to end with the alert displayed on the webpage

**Comment by TKDickson** [comment] 2024-09-24 20:57
Whoa, wasn't expecting @theodur to respond so quickly. One other thing:
- If I log into the mobile app and wait 45 minutes (I don't know where I have this number from, but that's the number of minutes I have notes to wait, to require re-authentication in the app), then I am logged into the VA H&B mobile app still, but no matter how many times I close and reopen the SSO-enabled webview, I am never logged in on the website. Both iOS and Android. I wonder if this has anything to do with the overall refresh issue #9615

**Comment by TKDickson** [comment] 2024-09-24 20:58
@theodur for loss of internet, I'm turning off the internet *before* tapping on the link to open the webview. (So go to appointment list page in app, turn off internet, tap on link)

**Comment by theodur** [comment] 2024-09-24 21:18
@TKDickson For re-authentication, we're talking about when the app tries to reauthenticate by hitting the `https://staging.va.gov/v0/sign_in/refresh` endpoint after it's been idle for some time right? It sounds like what's happening is that endpoint is returning a new access token (which is expected) but _isn't_ returning a SSO device_secret that is returned after initial login. So whenever the API call is made to get the SSO cookies, we're using the new access token with the old device secret, which might be causing some issues. I briefly looked through the SSO documentation, and didn't see anything about getting a new device secret when reauthenticating, so I'm not sure how that would be addressed. I'll have to dig into that

**Comment by theodur** [comment] 2024-09-24 21:25
Ahh, I haven't tested turning the network off before navigating to the Webview. Not sure whether that's just an OS difference with how iOS and Android is handling no access to internet. That a tricky one 🤔 off the top of my head I'm not sure what/if something can be done about that, but I can dig into it and see

**Comment by theodur** [comment] 2024-09-26 21:08
For this issue: 

> If you have the webview open (when the access token expires/5 minutes), both platforms exhibit the same behavior. You are 'still logged in' on the page that's showing, you are logged out on the next page you navigate to, then you're logged back in again on the next page after that. Or if you close and reopen the webview, you're correctly logged in. Seems more like a future enhancement-y type of thing to address (presumably on the web side?)

I tried reproducing this (opened an authenticated WebView, waited 5 minutes, and then navigated to other pages) but I was still logged in on all subsequent pages I visited. Not sure whether this might be an intermittent thing 🤔. Were there specific steps you took to see the intermittent signed-out/signed-in behavior?

Also took a look into:

> iOS handles loss of internet better than Android (iOS will load the webview logged in after loss of internet; Android will load it logged out so you have to close and reopen the webview for the SSO to work after loss of internet)

This one is interesting, if the internet is off before tapping the link to open the WebView, I'd imagine the API call to fetch the SSO cookies (which kicks off right as soon as the WebView is launched) would fail. We don't code in place to rerun the SSO cookies API call on reload, so I wouldn't even expect iOS to be logged in after regaining an internet connection and reloading the page.

Regardless, just to be safe I added logic that should fetch SSO cookies if the user is attempting to reload a WebView that failed to load due to lack of internet or any other resons, so this should be fixed now

**Comment by theodur** [comment] 2024-09-27 05:56
I have a potential fix for 

> If I log into the mobile app and wait 45 minutes (I don't know where I have this number from, but that's the number of minutes I have notes to wait, to require re-authentication in the app), then I am logged into the VA H&B mobile app still, but no matter how many times I close and reopen the SSO-enabled webview, I am never logged in on the website. Both iOS and Android. I wonder if this has anything to do with the overall refresh issue

coded locally, but for some reason the API was acting wonky on me when I was trying to test. I'll have to test my fix when I'm back in to see if it works

**Comment by theodur** [comment] 2024-09-30 19:13
> I have a potential fix for
> 
> > If I log into the mobile app and wait 45 minutes (I don't know where I have this number from, but that's the number of minutes I have notes to wait, to require re-authentication in the app), then I am logged into the VA H&B mobile app still, but no matter how many times I close and reopen the SSO-enabled webview, I am never logged in on the website. Both iOS and Android. I wonder if this has anything to do with the overall refresh issue
> 
> coded locally, but for some reason the API was acting wonky on me when I was trying to test. I'll have to test my fix when I'm back in to see if it works

I was able to test this today and got it fixed ✅. This ticket is ready for QA to review again @TKDickson.

Note: As part of the changes for the fix above, I had to [remove the logic](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9412/commits/359038dee864f66415c606955d63f21cd9549d10#diff-f7f666a89a3902933dac5bfbd61eeeaf6bc035eaa11aa3f1f0f1d4a0ab6ecf16) that clears cookies when refreshing access tokens and when initializing a session with a refresh token. I don't even think these were needed in the first place, since we aren't manually setting cookies anywhere else in the app. Still wanted to point out that you might want to test those bits of functionality (although I think you already will, since you'll be testing SSO after the access token gets refreshed

**Comment by TKDickson** [comment] 2024-10-01 17:59
On a build from yesterday with all the latest changes:
* Logging in to the app and opening an SSO webview works (signed in, in webview)
* Closing the webview, leaving the device alone for 5 minutes, and re-opening the SSO webview works (signed in, in webview)
* Closing the webview, leaving the device alone for 45 minutes, and re-opening the SSO webview still does NOT work (NOT signed in, in webview). Closing and reopening the webview, navigating around in the app to re-call APIs to double-check that the user is still logged in for the app - none of this works. In fact, at this point, forceclosing the app and logging back in via biometrics STILL doesn't result in SSO working in the app. I had to use the 'sign out' button, and log back in with username and password, in order to 'restore' SSO functionality in the app.

**Comment by TKDickson** [comment] 2024-10-01 21:40
@theodur 

> Do you know what happens at 45 minutes that makes that duration significant?

I don't have a specific reason for 45 minutes (and I haven't tried testing at every X minute intervals to see where it fails - 5 minutes works, but what about 15 minutes? 30 minutes? etc. I just know that 45 definitely doesn't.) When I thought up the test case, I was trying to aim for "the website would require reauthentication but ideally you'd be using biometrics to get into the app", but was unfortunately/fortunately still logged in and so ran into this issue instead.

> Was this happening before my latest changes as well?

I'll have to double-check tomorrow. My notes that I'm referring back to are inconclusive.

**Comment by dumathane** [comment] 2024-10-02 13:32
@theodur is there a way we could easily output the cookies on like a developer menu screen for Therese? She could then go and check it every X amount of time and see what's there, draw conclusions on whether we are losing it or it's for some reason losing functionality? We should also just maybe schedule a troubleshooting meeting at this point.

**Comment by TKDickson** [comment] 2024-10-02 19:14
[DSVA slack thread](https://dsva.slack.com/archives/C04LFGY2SJK/p1727880350045999) trying to figure things out with identity teams

**Comment by TKDickson** [comment] 2024-10-04 15:09
SSO does not work under these conditions (both iOS and Android):
* Erase the app & reinstall it (have no cookies or tokens, guaranteed)
* Log in via UN/PW, enable biometrics, and DO NOT open an SSO webview. 
* Forceclose the app, and log in with biometrics (if, inexplicably, your Android biometric login fails, repeat the prior step & this one until you get an Android biometric login that works)
* Open an SSO webview. It isn't logged in, iOS or Android.

**Comment by theodur** [comment] 2024-10-08 03:12
@TKDickson I fixed and confirmed the above now works in my latest changes ✅

**Comment by TKDickson** [comment] 2024-10-08 15:02
Closed my initial test run, and opened up [a new one ](https://dsvavsp.testrail.io/index.php?/runs/view/5999&group_by=cases:section_id&group_order=asc)(since there have been significant enough changes under the hood for web and mobile to warrant reresting)

**Comment by TKDickson** [comment] 2024-10-08 16:53
Currently unable to test with any credentials other than id.me. MHV workaround is broken #9830, TUD (which was necessary to log in with login.gov) has apparently been deprecated (see screenshot. I tried logging in with credentials from TUD anyways, as well as from the vault, and neither of them worked - got a post 2FA error from TUD, and couldn't get through 2FA with the vault), and all of the stored DSLogon credentials are either deprecated or locked out because of failed attempts. Bringing up as a blocker at standup today.
<img width="1618" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUl3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65bf56ce425e45a5acdbebf0041b696d1d6cddcf/image.png" alt="image.png" />

**Comment by TKDickson** [comment] 2024-10-08 20:39
Bug tickets above #9832, #9833 were signed off on by stakeholders; this is OK to merge to develop in an off state.

**Closed** 2024-10-09 13:49 UTC
Labels: QA, front-end, global, QA 2
