### ISSUE TITLE
CU - Remove testID from VABulletList component

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va-mobile-app#5779] opened 2023-05-23 18:06 UTC
## Proposed Change

The VABulletList component uses a testID which is not needed. The testID necessitates an extra workaround when using the `boldedTextPrefix` and `boldedText` props because the testID omits those props, so they aren't read by the screen reader. This ticket covers:

1. Removing the testID from the VABulletList component
2. Ensuring the a11yLabel prop still works correctly with testID gone
3. Auditing existing usage of VABulletList and removing unneeded a11yLabels which were only added as workarounds (see above)

## Why Should We Prioritize?

Engineers will assume VABulletList announces bolded text, but due to the testID issue, it does not. This could cause a11y issues. In addition, adding labels as workarounds takes extra time and is error-prone. Removing the testID will fix these issues.

## Coding Time Estimation

3
	
## Testing Considerations

All uses of VABulletList will need to be checked with screen readers on iOS and Android. There are 17 files using VABulletList as of May 2023.

## Checklist
[X] Add the front-end label tag

[X]  Attach to the Frontend epic for engineering initiatives

**Comment by timwright12** [comment] 2023-12-11 15:41
@alexandec do we still need this ticket?

**Comment by juancstlm-a6** [comment] 2024-09-24 22:04
I believe this to have been completed in https://github.com/department-of-veterans-affairs/va-mobile-app/commit/d5721ee63a425662d8be80b518f085994689d97f#diff-580f6e35c23c01211dbeffcd729de2a8cb34ec1eaec152aef1a6c67474b5d84dL98

**Comment by TKDickson** [comment] 2024-09-25 17:16
@alexandec for ^

**Comment by alexandec** [comment] 2024-09-25 18:12
@juancstlm-a6 @TKDickson it looks like points 1 and 2 are completed already, but point 3, auditing existing usage of VABulletList and removing unneeded a11yLabels which were only added as workarounds, is not. Searching the repo for "boldedText" still shows examples of VABulletList usage where there are a11yLabels which should no longer be needed.

**Comment by juancstlm-a6** [comment] 2024-09-25 18:19
@alexandec thanks for the clarification. 

I'll take a look at point 3 as 1 and 2 have been completed

> 3. Auditing existing usage of VABulletList and removing unneeded a11yLabels which were only added as workarounds (see above)

**Comment by TKDickson** [comment] 2024-09-25 18:22
@juancstlm-a6 FYI about the existence of [this PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9620) (should be merging into develop sometime today) as you start an audit

**Comment by juancstlm-a6** [comment] 2024-09-27 18:10
@alexandec For clarification the VABulletList should announce `boldedText` and `boldedTextPrefix` without the need for a  `a11yLabel` 
It is kind of implied that by completing #1 this will enable the aforementioned feature.

**Comment by juancstlm-a6** [comment] 2024-09-27 19:35
For Items that include a `boldedText` and a `a11yLabel` with a helper `a11yLabelVA()` helper. Ex: Below 
```javascript
{
  text: t('prescription.details.banner.bullet1'),
  boldedText: ' ' + t('or'),
  a11yLabel: a11yLabelVA(t('prescription.details.banner.bullet1')) + ' ' + t('or'),
}
```
 I will be leaving those alone as is and not removing the `a11yLabel`  since the `a11yLabelVA` function replaces the "VA" into "V-A" for accessibility. 

We could, and I would be glad to, create a separate ticket where we can modify the `accessibilityLabel` of VABulletList to automagically apply this helper function like `accessibilityLabel={a11yLabelVA(a11yLabel || '')}` so that we can further reduce the need for a `a11yLabel` and save time and reduce potential mistakes where a translation string did not get wrapped with the helper when it should have. This would in turn allow us to remove the `a11yLabel` from the example above and just have the following:
```javascript
{
  text: t('prescription.details.banner.bullet1'),
  boldedText: ' ' + t('or'),
}
```

**Comment by alexandec** [comment] 2024-10-01 00:22
@juancstlm-a6 thanks for working on this, and I agree that the a11yLabelVA function is still needed in some cases. I checked out your draft PR and left a comment there about a possible method of simplification. See what you think.

**Comment by TKDickson** [comment] 2024-10-03 15:31
Over my ticket capacity, so not working on this currently. Adding blocked label.

**Comment by TKDickson** [comment] 2024-10-04 17:17
Picking this up now, removing blocked label

**Comment by TKDickson** [comment] 2024-10-04 17:40
Checking written & announced content for correct & matching formatting (ex: bolding) on all screens with bolded text in VA Bullet lists:

- [ ] LOA gate
- [ ] Gender ID what to know
- [ ] Reply help
- [ ] RX details 'banner' (for transferred meds, on med details screen)
- [ ] Appeal details for active appeal
- [ ] Claim details for closed claim
- [ ] Rx history 'not authorized' (Judy should have this)
- [ ] Not enrolled in SM (can mock via authorized services)

**Comment by TKDickson** [comment] 2024-10-04 19:21
OK, tickets written for the bugs found during testing & not caused by this change, #9800 ad #9801 mentioned in prior comment.

The Android UI automation scripts in the PR are fine (just the one failure for URL links in the messages script that has also been failing in develop), but there was [an app crash in Profile for iOS](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11184165287?pr=9736) that I haven't seen before. Re-running the script to see if it was a one-off/flake, and if not I'll dig in to what's going on there.

**Comment by TKDickson** [comment] 2024-10-07 13:28
iOS passed on a re-run, this is good to go

**Closed** 2024-10-07 16:16 UTC
Labels: front-end, code upkeep, Good first issue, global
