### ISSUE TITLE
BUG - Sev 2 - Android - sightings of "Text strings must be rendered within text component" when attempting sign in

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#7565] opened 2023-12-15 23:11 UTC
## What happened?

When attempting log in on some android builds we are getting a red screen with messaging: "Text strings must be rendered within text component"
## Specs:

- Device: various
- OS: android
- User Account: n/a
- Accessibility State: n/a

## Steps to Reproduce

Attempt sign in on an android device, roll the device, see if you get the luck red screen of non-log-in-ness

## Desired behavior

You should be able to sign in to the app without an error screen

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High 
- Frequency: Low 

- 2 - High

## Screen shot(s) and additional information

<img width="450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--291fd718ac28504a6a2c337644b06e12a703d8b1/Screenshot_20231212-130307.png" alt="Screenshot_20231212-130307.png" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment] 2023-12-20 22:15
Comments from DSVA slack thread about this (sorry many of them are pictures, sigh):

<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUo2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09a16747d47d4e15811f19f43de3acc0e7eff4ab/image.png" alt="image.png" />

It's not a recent problem, we do this a lot:
<img width="199" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU42QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02b192474f4a5ed53c08a4809018d7504d744a18/image.png" alt="image.png" />

**Comment by bischoffa** [comment] 2024-01-03 16:47
@ajsarkar28 fyi. Typically Sev-2s have gotten prioritized in the next sprint to get work.

**Comment by bischoffa** [comment] 2024-01-17 18:59
[@ajsarkar28](https://github.com/ajsarkar28) this ticket has last sprint on it but not worked. if its being pulled in this sprint can you update the sprint tag on this?

**Comment by theodur** [comment] 2024-01-26 06:30
@DJUltraTom @TKDickson Do either of you remember which point in the login process you saw this error? After looking at potential relevant screens and their subcomponents (Login, Sync, Home), at first glance I'm not seeing anything that looks like the offending code 🤔

**Comment by TKDickson** [comment] 2024-01-26 15:41
Ah, shoot. Ticket documentation fail, and a fair question. 

@theodur I am.... maybe 60% confident that it was showing up right when I hit the "sign in" button on the prelogin screen. If you can trust my memory on that one, which I don't but I feel like we don't have better options 😭 , I don't know if that was on first login (so I was going from signin to the LOA gate) or subsequent login (so it would have been opening up the auth webview).

**Comment by theodur** [comment] 2024-01-30 23:22
@TKDickson Thanks for confirming!

I have good news and bad news.. I guess they're the same new in this case; I'm not able to reproduce the bug at all 😓 even when attempting on the builds this was seen in (1061 & 1064 for Android). I tried multiple times with different scenarios (first login, and subsequent login). A few things that come to mind:

- I may just be "unlucky" with reproducing the error, although I really tried pushing my luck
- This issue may have been fixed by other work
- This issue may have been caused by some abnormality in the data that was received from the API at that time, and may not be applicable anymore

It's also strange this error would only be seen on Android. Since it's a rendering issue with React, it should have been happening in iOS as well.

I confirmed with Therese that we're good to close this for now, and if we notice this happening again, we can reopen this

**Closed by theodur** 2024-01-30 23:22 UTC
Labels: sev-2, bug, qa, front-end, scrubbed, global
