### ISSUE TITLE
BUG - SEV-3 - iOS - App crashes when the file for an uploaded attachment is missing

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#9537] opened 2024-09-04 18:14 UTC
## What happened?

We have had a few instances of the app crashing when a user tries to open a file that doesn't exist. We don't know how you select a file that doesn't exist - that's probably not a problem for the app, but this feels like something that shouldn't trigger a crash, but rather an error message.

[Read the crash report for this issue](https://console.firebase.google.com/u/0/project/va-mobile-app/crashlytics/app/ios:gov.va.vamobileapp/issues/574877b750463c50822d50a5ee224fbd?time=last-seven-days&types=crash&sessionEventKey=13f6559fb6784e3a9178de4dfc52ba3b_1987862472124724953)

## Specs:

- Device: iPhone 15 Pro Max
- OS: iOS
- App version: 2.35.0

## Steps to Reproduce

No steps were specified, this is from a crash report, but based on the breadcrumbs it looks like it is happening in a message attachment.

## Desired behavior

If possible, the app should error instead of crashing

## Bug Severity

Labeling as a sev-3 bug because it doesn't happen much, just feels like something we might be able to help clean up.

## Error

```
Fatal Exception: NSInternalInconsistencyException
-[UIDocumentPickerViewController initForExportingURLs:asCopy:] must be called with a URL pointing to an existing file: Error Domain=NSCocoaErrorDomain Code=260 "The file “VA Form 10-10172.pdf” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///var/mobile/Containers/Data/Application/5E6C8740-CEE4-4F59-8129-3741EE03999F/Documents/VA%20Form%2010-10172.pdf, NSFilePath=/var/mobile/Containers/Data/Application/5E6C8740-CEE4-4F59-8129-3741EE03999F/Documents/VA Form 10-10172.pdf, NSUnderlyingError=0x302002a30 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by alexandec** [comment] 2024-09-09 17:45
I did a short investigation into this and was unable to reproduce it. I added a line to unlink the file right before opening it:

```
const downloadFileAttachment = async (file: SecureMessagingAttachment): Promise<boolean | undefined> => {
  const filePath = await downloadFile('GET', file.link, file.filename)
  if (filePath) {
    await unlinkFile(filePath) // I added this line to unlink the file
    await FileViewer.open(filePath, {
      onDismiss: async (): Promise<void> => {
        await unlinkFile(filePath)
      },
    })
    return true
  }
}
```

then I logged in as user+41 on staging and clicked on a Secure Messaging attachment. The resulting screen isn't clear about the error, but it is recoverable and doesn't crash the app:

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0srQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2ccb3f0eb17e21da35ada2bf13a666727668d7e/Simulator%20Screenshot%20-%20iPhone%2015%20-%202024-09-09%20at%2011.35.51.png" alt="Simulator Screenshot - iPhone 15 - 2024-09-09 at 11.35.51.png" />

Based on [some SO comments](https://stackoverflow.com/questions/37109130/uidocumentpickerviewcontroller-returns-url-to-a-file-that-does-not-exist), it's possible that the error occurs when the downloaded attachment is placed on an iCould drive but there's poor network connectivity, or that some kind of iOS bug is getting triggered in a certain rare case. I think this will be challenging to reproduce since it appears to be happening at a lower level than the react-native-file-viewer package we are using.

**Comment by Sparowhawk** [comment] 2024-09-24 16:39
@alexandec @timwright12 we can add a .catch block to the Fileviewer.open line and manually throw an error

We would just need content and design input to determine what is displayed afterwards @mistymg @wavelaurenrussell 

CC: @dumathane @ala-yna

**Comment by alexandec** [comment] 2024-09-24 17:09
@Sparowhawk we could try a catch block, but without being able to properly reproduce the error and see the `Fatal Exception: NSInternalInconsistencyException` message, I don't think there's any guarantee we're actually solving this issue. I wasn't able to reproduce the error in my initial testing, as described above.

My guess is that Fileview.open is calling a native iOS method that's erroring out, and Fileview.open isn't handling that particular native error correctly. Adding a .catch block in JS will only protect against native errors that Fileview.open itself is catching.

**Comment by TKDickson** [comment] 2024-10-22 20:47
Closing this per 'not fixing' policy (low severity externally reported issue that we can't reproduce internally). If we get more information to be able to reproduce (more detailed bug reports) or severity increases (probably an increase in people seeing the crash), etc, can reopen.

**Closed by TKDickson** 2024-10-22 20:47 UTC
Labels: sev-3, bug, QA, front-end, Health
