### ISSUE TITLE
Create & Implement Deeplink Home Screen Button Component 

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7876] opened 2024-01-31 18:26 UTC
**AC**

**Component Creation**
- A new home screen button component is created, that reflects the designs in this [figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3053-3321&mode=design&t=hrushtBNvdTcfk7k-0), which can deeplink to other parts of the application when clicked 
- VQA by Lauren and Therese is required to complete this ticket

**Component Implementation**
- The button component, created above, is implemented for the following features and uses the backend logic in the corresponding tickets:
  - Appointments - [logic ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7379)
  - Prescriptions - [logic ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7381)
  - Claims - [logic ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7378)
  - Secure messages - [logic ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7380)
  - For each of the feature modules, the content matches the linked Figma file 
  

**Accessibility & Content** 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by TKDickson** [comment] 2024-02-20 15:42
Shared cases with #7935, [link to testrail cases](https://dsvavsp.testrail.io/index.php?/cases/view/59376)

**Comment by TKDickson** [comment] 2024-03-01 19:12
Things found while testing:
* Need to update order of buttons (when all present) to match Figma. Figma is Appointments, Claims, Messages, Prescriptions (alphabetical order). Branch is currently Appointments, Claims, **Prescriptions, Messages**.
* Claims is no longer deeplinking to the claims list (it did during original implementation, has regressed at some point). All other buttons still correctly deeplinking. (Note to self that I still want to test claims deeplinking with and without the history/list interstitial page)
* Deeplink button is announced as a button, instead of a link. [Says link in the Figma for a11y annotation.](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3053-3321&mode=design&t=6QDViv6lsi244OOa-0)

**Comment by TKDickson** [comment] 2024-03-01 20:34
[TestRail run](https://dsvavsp.testrail.io/index.php?/runs/view/5241&group_by=cases:section_id&group_order=asc). The issues above are all I've found (plus [a platform difference in voice access command language that I pinged Brea about in slack](https://adhoc.slack.com/archives/C063KLSMVAR/p1709325087597659?thread_ts=1709324953.031519&cid=C063KLSMVAR), I don't think it's a bug)

**Comment by theodur** [comment] 2024-03-04 18:26
@TKDickson All the issues you found should be fixed now. The claims deep link issue was due to the `develop` merge into the feature-xl branch. At some point in `develop` it looks like the claims history screen name was changed from `ClaimsHistory` to `ClaimsHistoryScreen`. That just needed to be updating in the linking config in the feature-xl branch

**Comment by TKDickson** [comment] 2024-03-04 19:00
Aha. @theodur thank you for the explanation, I was definitely wondering how that could have broken in the interim. Will build and check things out now.

**Comment by TKDickson** [comment] 2024-03-04 19:43
All fixed!
* Order with all buttons now matches figma
* Screen reader announces link
* Brought to claims in deeplink (and back to the benefits landing page when pressing back, regardless of claims letters access, which is actually pretty darn cool I think)

Sending to Lauren for VQA signoff.

**Comment by wavelaurenrussell** [comment] 2024-03-04 21:11
Found a few things: 

1. Font style for Feature titles - should be Bitter Reg (400). Font size is 22px with a line height of 24px
2. Box shadow looks a little subtle. Can we confirm the style? (a guess: might need to darken alpha channel just a hair 40% to 50%)

**Comment by theodur** [comment] 2024-03-04 22:35
@wavelaurenrussell Just confirmed that the font being used is Bitter Regular 400 and the font size is 22px. The only thing I'm seeing that's different is the line height, which I have set to 30px because for some reason at the time, the Figma design was showing the line height as 20px which seemed off since that's smaller than the font size, so I defaulted to 30px. I'll go ahead and update that to 24px. Just want to make this is what you were seeing in your build also:
<details><summary>Screenshot toggle</summary>

![IMG_0146](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/6fbec60c-b2a5-47cc-9e39-00cce3e9b7c8)
</details>

The drop shadow is currently set to 40%, here's what the difference looks like moving from 40% to 50%:

40%(left) / 50%(right): 
<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/d502bb86-e51d-4848-a237-6b6d9c5b17ab" width="49%" />&nbsp;&nbsp;<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/d97a8f0d-4837-446a-aa6e-a46d320a242f" width="49%" />

Does 50% look good, or should we go higher on that?

**Comment by wavelaurenrussell** [comment] 2024-03-04 23:02
@theodur cool. Let's leave the shadow like it was originally (Figma specs), and I'll reassess it when everything is done. The font displays as intended in iOS, but incorrect for Android. Here's what I see on my test device (Motorola Ace):

<img width="361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1d0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71401fb3ec7743c58cb35f50c405b2c48175864a/Screenshot%202024-03-04%20at%2018.01.00.png" alt="Screenshot 2024-03-04 at 18.01.00.png" />

**Comment by theodur** [comment] 2024-03-04 23:18
@wavelaurenrussell That's so strange the font isn't being applied on your build, because on my Android emulator, it's showing the font being applied. I'll try tinkering with it on a physical device and see what's going on.

And cool, I'll leave the opacity as is for now. Thanks for confirming!

**Comment by theodur** [comment] 2024-03-06 02:29
I fixed the font issue with Android. For some reason, we ignore the entire `android/app/src/main/assets` directory in our `.gitignore`, which I'm assuming is to prevent build specific files like `*.bundle` from being synced. But in doing so, we're also preventing the `android/app/src/main/assets/fonts` directory from being synced, which is needed for the fonts to take effect on non-local Android builds. The reason why the font was working on my locally is because local builds probably pull the assets from the `VAMobile/assets/fonts` directory, which is platform independent.

This is good for QA again @TKDickson @wavelaurenrussell

**Comment by TKDickson** [comment] 2024-03-06 14:31
I saw the correct font in Android and sent Lauren the build info for VQA.
Also confirmed - the Voice Control for iOS is now much more intuitive ("tap Appointments" instead of "tap Appointments 2 in the next 7 days"), Android is still "tap appointments".

Testing done. My signoff is just pending VQA signoff.

**Comment by TKDickson** [comment] 2024-03-06 14:54
VQA signoff done in Slack; this ticket is ready to merge to XL.

**Comment by TKDickson** [comment] 2024-03-06 14:55
Merged into XL; closing ticket.

**Closed by TKDickson** 2024-03-06 14:55 UTC
Labels: QA, front-end, Post Planning Add, global, QA 2
