### ISSUE TITLE
Create VA Resources Section with Populated States

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7971] opened 2024-02-12 19:49 UTC
**Overview**
This ticket covers the creation of the home screen's VA Resources section. The content in this section is covered by the component creation and implementation [ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7599)

For all visual elements in this ticket, reflect the designs in this [Figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=2723-916&mode=design&t=iNmoPBQvnErOJAu5-4)

**Header**
- A header that says VA Resources is implemented. 

**Populated**
- The Contact Us Link Row component should display
- The Find a new VA Location Link Row component should display

**Accessibility & Content** 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by TKDickson** [comment] 2024-02-20 16:25
[Test rail cases link](https://dsvavsp.testrail.io/index.php?/cases/view/59280) - cases are shared with #7599 and #7853

**Comment by TKDickson** [comment] 2024-03-13 14:43
@theodur the VA Resources section UI is pretty much not working at all, iOS and Android, in the on demand build I made today. No labels, touch target extremely small (or so it seemed), and the > icon not sized well with the row (maybe because labels missing).

I haven't really tested at all, just building & opening the app & going "nope, something went wrong here"

<img width="593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkhaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--723cbe6ea56bd6951399af34b8397e726c61e955/image.png" alt="image.png" />

<img width="593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkRaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21576a05e96f7f6f7436458834bf2fc7fc5eb278/image.png" alt="image.png" />

**Comment by theodur** [comment] 2024-03-13 17:55
@TKDickson I fixed the issue, you're good to review again!

**Comment by TKDickson** [comment] 2024-03-13 19:11
Phew, much better!

One thing that I saw (that, I just confirmed, is not happening in develop) is this weird 'screen location' behavior when I'm exiting the Contact VA screen to go back home. [Here's a video](https://drive.google.com/file/d/1fe415bCgN77R-LqtPtZfGyzse04t7RbW/view?usp=sharing), it's happening iOS and Android.

Find a VA location is first, and see how you're 'where you expect' on the home screen when you go back. Then when exiting Contact VA, you're seemingly/suddenly scrolled down past the VA resources section on the home screen when you first go back and then the screen drops back into where you'd expect it to be.

Is there anything we can do about this? And if yes, should it be a separate bug ticket? (IDK if it's actually caused by this change, seems likely it's an interaction of a bunch of stuff with this development that should/could be addressed on its own)

**Comment by TKDickson** [comment] 2024-03-13 19:11
whoops. @theodur for the above comment.

**Comment by TKDickson** [comment] 2024-03-14 14:00
Moved the above issue to an AC on the state management home screen ticket #8183, which means that these tickets (this + #7599) are ready for VQA.

**Comment by TKDickson** [comment] 2024-03-15 00:30
Merged to XL (VQA signoff in #7599), closing.

**Closed by TKDickson** 2024-03-15 00:30 UTC
Labels: QA, front-end, global, QA 1
