### ISSUE TITLE
BUG - Sev-3- All - Certain AF waygates aren't working in the developer screen on the app

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8279] opened 2024-03-28 20:18 UTC
## What happened?

The following waygates either don't work in demo mode when you set them or say they are now undefined:
- WG_ClaimsHistory
- WG_EditAddress
- WG_SecureMessaging
- WG_PrescriptionHistory
- WG_Login
- WG_Developer
- WG_Health

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

1. Login to staging or open demo mode
2. Navigate to the developer menu and click remote config
3. Notice that WG_SecureMessaging, WG_PrescriptionHistory, WG_Login, WG_Developer, and WG_Health say undefined
4. Enable one of AF's use cases for either WG_ClaimsHistory or WG_EditAddress. Notice it doesn't work

## Desired behavior

All waygates should be editable in the developer screen.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by dumathane** [comment] 2024-04-12 14:23
WG_Login appears to be working fine via my steps:
![image](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/46909588/6c22d4d8-592e-4937-a15c-a90f91d6b538)

**Comment by dumathane** [comment] 2024-04-12 15:14
Edit Address appears to work fine as well.
![image](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/46909588/58368dd6-74a1-4809-bf2b-df4bf3dc5f98)

**Comment by TKDickson** [comment] 2024-04-12 17:09
Alrighty.
* Claims history was a real bug (change in the screen name after AF was released, maybe 3 versions). We're fixing that, and adding a note to the AF documentation about how we'll need to be careful in some versions
* Edit address neither Binny nor I could reproduce the problem, so... tentatively just scooting right on past that one
* The 'undefined' was a testing tool thing -- for AF waygates where there was existing setup in firebase (aka all of the ones listed in this ticket, because of testing, Redis, and Lovell), they would come in on a fresh install as undefined. You could still totally use the testing tool (by toggling the enabled toggle twice) but Binny is also changing the defaults in Remote Config to be enabled to avoid this in the future.

Should be attached to a PR and moving through the usual process today for the actual code change.

**Comment by TKDickson** [comment] 2024-04-15 16:50
<img width="391" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHRnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09b3dc09199654576b2d1e2df617c5b59be048cc/image.png" alt="image.png" />

Per comment immediately prior - claims history (now 'claims history screen' to match the screen name which changed) is now working.

**Comment by TKDickson** [comment] 2024-04-15 20:16
[Claims](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/8693264949) and [AF](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/8694056542) detox scripts passing. I think we're good to merge to develop.

**Comment by TKDickson** [comment] 2024-04-16 15:02
No further testing needed in develop, closing.

**Closed** 2024-04-16 15:02 UTC
Labels: sev-3, bug, QA, Closed - Deployed/Fixed, scrubbed, global, Found with Detox
