### ISSUE TITLE
BUG - sev-3 - Android - Get directions integration is broken

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7046] opened 2023-10-19 17:00 UTC
## What happened?

Get directions is broken for google maps/Android:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3hVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abc0add9c3f813330b9d0eacf8e6330b042f1b0f/image.png)

Apple/iOS is working fine:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14ab12665c0c8af377de3041ca6913ce21dcb7ca/image.png)

## Specs:

- Device: Google Pixel 6
- OS:
- User Account: any scheduling user - I think I was using royal.tester@id.me at the time
- Accessibility State:

## Steps to Reproduce

Home > Health > appointments > [pick an upcoming appointment with a location from the list] > get directions

## Desired behavior

Should pull up the location correctly in the map app of the user's choice

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 
- 
Marking as low impact because the users have the correct address in the app, and can copy-paste it over (it's not like we're sending them to the wrong place/it's clearly broken) so there's a reasonable workaround.

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by theodur** [comment] 2023-10-31 14:49
The issue was caused by the address, location name, and latitude/longitude being added to the Google Maps URL. The [Google Maps Platform documentation](https://developers.google.com/maps/documentation/urls/get-started#search-parameters) states that the destination parameter can **either** be `a place name, address, or comma-separated latitude/longitude coordinate`, but it doesn't mention anything about adding multiple options. I updated the URL to only contain the address in the destination parameter, and it'll fall back to adding only the latitude/longitude if the address isn't available for whatever reason (it should almost always be available). The changes in the PR for this don't affect iOS links.

**Comment by DJUltraTom** [comment] 2023-11-02 00:02
verified that an address now populates to a location on the map and seems to give me directions to said facility
QA approves this code[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62c5e51761b64a9ac9a50962479c9f565936b5dc/Screenshot_20231101-165837.png)

**Comment by DJUltraTom** [comment] 2023-11-03 19:18
verified this is working correctly on the overnight QA build, closing ticket

**Closed by DJUltraTom** 2023-11-03 19:18 UTC
Labels: sev-3, bug, qa, front-end, appointments, Closed - Deployed/Fixed, scrubbed, Post Planning Add
