### ISSUE TITLE
Test Tracking Referring URLs with an Email

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#8464] opened 2024-04-24 19:48 UTC
AC:
- Using the directions in this [slack conversation](https://dsva.slack.com/archives/C010R6AUPHT/p1713882403516199?thread_ts=1713450597.759209&cid=C010R6AUPHT) with VA Notify, generate and send a test email to yourself (probably Theo or Binny) that contains a dynamic link to the application
- Using the link in the email, test out the following scenarios:
   - iOS user with the app installed clicks on the link which opens the app 
   - Android user with the app installed clicks on the link which opens the app
   - iOS user without the app installed, clicks on the link which takes them to the app store
      - User then downloads and opens the app 
   - Android user without the app installed, clicks on the link which takes them to the app store
      - User then downloads and opens the app
- In all the scenarios listed above, the team is able to track where the user came fro. Specifically, that they are a new user or existing user that came to the app via the dynamic link in the test email
   - Ideally, the dynamic link has UTM parameters for more granular analysis

**Comment by theodur** [comment] 2024-05-02 23:29
I confirmed all scenarios are working correctly. I tested by sending a test email via https://staging.notifications.va.gov/ to my VA email, and forwarding that email to my Ad Hoc email (since I can't access my VA email on my mobile phones). Here are screen recordings of each scenario:

<details><summary>iOS user with the app installed clicks on the link which opens the app</summary>


https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/5d3092a7-debf-43c7-b5c8-34a4fc5a5561
</details>

<details><summary>iOS user without the app installed, clicks on the link which takes them to the app store</summary>

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/ba01e86c-f3b4-44d0-8469-33937a593df5
</details>

<details><summary>Android user with the app installed clicks on the link which opens the app</summary>

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/fb9884e3-19a8-4537-84a9-a139a66715fe
</details>

<details><summary>Android user without the app installed, clicks on the link which takes them to the app store</summary>

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/29ccdd9c-c5c2-418b-9fe8-4e08f4339879
</details>

**Comment by theodur** [comment] 2024-05-06 16:55
There's no code to review for this, but I moved it into the `Code Review` lane to signify it's awaiting some type of review (awaiting @ajsarkar28's return before closing this).

**Closed** 2024-05-14 17:36 UTC
Labels: front-end, Post Planning Add, global
