### ISSUE TITLE
ENG: Update buttons and links on global screens

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7798] opened 2024-01-24 15:24 UTC
The following list are the updates that need to be made to buttons and links on global screens within the app.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._
- [x] **[previous screen name]**
     - **Location:** Global / Header navigation
     - **Current component type:** Button
     - **Current style:** N/A
     - **Icon:** Chevron Left
     - **What happens?** Take the user back to a previous screen (home, profile, etc.)
     - **Recommended change:** Should be a link and not a button
- [x] **Skip**
     - **Location:** Global / Onboarding
     - **Current component type:** Button
     - **Current style:** N/A
     - **Icon:** N/A
     - **What happens?** Skips the onboarding carousel and redirects to the home screen
     - **Recommended change:** Should be a link and not a button
- [x] **Back**
     - **Location:** Global / Onboarding
     - **Current component type:** Button
     - **Current style:** N/A
     - **Icon:** N/A
     - **What happens?** Takes you to the previous page of onboarding
     - **Recommended change:** Should be a link and not a button
- [x] **Next**
     - **Location:** Global / Onboarding
     - **Current component type:** Button
     - **Current style:** N/A
     - **Icon:** N/A
     - **What happens?** Takes you to the next page of onboarding
     - **Recommended change:** Should be a link and not a button
- [x] **VeteransCrisisLine.net**
     - **Location:** Global / VCL panel
     - **Current component type:** Link
     - **Current style:** Tertiary
     - **Icon:** N/A
     - **What happens?** Native alert / You're leaving the app / redirects to veteranscrisisline.net
     - **Recommended change:** This is an external link and should have an icon indicator (external link icon).
     - 
- [x] **Done** (in onboarding carousel, as mentioned by Theo in comments)

**Comment by theodur** [comment] 2024-07-09 23:22
I didn't see it in this ticket, but looking through the audit spreadsheet, it says the `Done` button on the final screen of the onboarding carousel should be converted to a link also. That change will also be applied in the PR for this ticket since it's related

**Comment by TKDickson** [comment] 2024-07-11 15:12
At my WIP limit, so marking this as blocked

**Comment by TKDickson** [comment] 2024-07-17 15:06
@theodur I noticed during testing that the "close" button on large panels is currently a button. Confirmed in the audit spreadsheet it is meant to be a link (and was supposed to be included in this ticket, but missed - row 71).

I did a quick CTRL+F for "7798" and that one appears to be the last one intended to include here, can you make that change too please?

All of the other changes announcing as expected in iOS and Android (oneplus).

**Comment by TKDickson** [comment] 2024-07-17 20:59
Large panel 'close' is now also reading as a link. Approved to merge.

**Comment by TKDickson** [comment] 2024-07-18 14:23
Doesn't require further testing in develop; closing.

**Closed by TKDickson** 2024-07-18 14:23 UTC
Labels: eng, front-end, global, QA 1
