### ISSUE TITLE
Spike - Can we detect which service a user signed into the app with?

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#7221] opened 2023-11-07 14:54 UTC
This ticket is in support of [#7208](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7208).

We need to find out if we are able to add a message into the mobile app UI if a user signed in with MHV or DS_Logon.  More details in the linked ticket around acceptance criteria.

Frontend and backend should work together to figure this out.

**Definition of done**

- [x] We have a yes/no answer on whether we can do this
- [x] If we can't do it with the current APIs and data, what would it take?
- [ ] Any follow up tickets needed to complete the work are created

**Comment by jperk51** [comment] 2023-11-07 17:17
This data is definitely available on the BE as part of the user object. We currently use it in some access policies for certain features. I'll make a ticket for exposing that in the v2 user response and block this ticket with it

**Comment by jperk51** [comment] 2023-11-07 17:21
Actually we already return this info the FE in the field `signinService` as part of v2 user

**Comment by Sparowhawk** [comment] 2023-11-08 19:11
@timwright12 yeah they return this to us in v2 user:

export type PersonalInformationData = {
  firstName: string
  middleName: string | null
  lastName: string
  signinEmail: string
  signinService: string
  birthDate: string | null
  fullName: string
}

This ticket can be closed or repurposed to creating the analytics needed to capture this

**Comment by timwright12** [comment] 2023-11-08 21:00
Can we 100% confirm the strings that come back. Specifically that we can see MHV and DSLogon? I see IDME in the [docs](https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v2~1user/get)

**Comment by jperk51** [comment] 2023-11-08 22:36
We definitely get them all back. There's an enum on v1/user in the docs. That's the same for v2 the enum just didn't get carried over in the docs. The list you have there is correct afaik, but I can confirm tomorrow

**Comment by timwright12** [comment] 2023-11-09 13:07
I saw one enum that included all for an another that only had three in there

**Comment by jperk51** [comment] 2023-11-14 18:49
These are the correct strings: 
IDME
DSL
MHV
LOGINGOV

I'll make sure the v2 docs get updated with the enum

**Comment by Sparowhawk** [comment] 2023-11-15 01:55
@timwright12 is there anything else you need on this ticket?

**Comment by timwright12** [comment] 2023-11-15 13:02
@Sparowhawk yeah, the last AC is "Any follow up tickets needed to complete the work are created" seems like that's just the documentation update from @jperk51 so once that's complete we can close this out

**Comment by jperk51** [comment] 2023-11-15 18:44
Should be fixed today. I didn't bother making a new ticket since it was less than a minute of work to update the docs

**Comment by timwright12** [comment] 2023-11-15 19:02
@jperk51 ok, just drop the link here when you're done and close this out

**Comment by jperk51** [comment] 2023-11-16 18:09
Docs are updated: https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v2~1user/get

**Closed by jperk51** 2023-11-16 18:09 UTC
Labels: front-end, Post Planning Add
