### ISSUE TITLE
Investigate Claims Decision Request 404s

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8324] opened 2024-04-08 14:51 UTC
We've been having a ton of 404s for decision requests. Try to figure out why that's happening. 

Note: We had an issue like this in staging recently and it was caused by claims being on LH and decision requests being on EVSS. You might want to start by turning claims off from LH in prod and see if the 404s also drop. 

[datadog logs](https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&graphType=flamegraph&groupMapByOperation=null&panels=qson%3A%28data%3A%28activePanelKey%3Aresource%2Cresource%3A%28resourceName%3AMobile%253A%253AV0%253A%253AClaimsAndAppealsController%2523request_decision%2CresourceID%3A8333ac3c792a8596%29%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%2Csearch%3Adeci%29%2Cversion%3A%211%29&shouldShowLegend=true&sort=time&spanID=944352877405408819&spanViewType=metadata&summary=qson%3A%28data%3A%21f%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Aratio%2CbreakdownAs%3Aabsolute&view=spans&start=1712499498147&end=1712585898147&paused=true)

**Comment by Tonksthebear** [comment] 2024-04-11 21:45
It's looking like the 404s are indeed caused by something funky with the lighthouse -> EVSS combo

[Lighthouse on](https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&graphType=flamegraph&groupMapByOperation=null&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%2Csearch%3Acl%29%2Cversion%3A%211%29&s3BucketDetails=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&shouldShowLegend=true&sort=time&spanViewType=metadata&summary=qson%3A%28data%3A%21f%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Aratio%2CbreakdownAs%3Aabsolute&view=spans&start=1712781000000&end=1712784600000&paused=true)
[Lighthouse off](https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&graphType=flamegraph&groupMapByOperation=null&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%2Csearch%3Acl%29%2Cversion%3A%211%29&s3BucketDetails=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&shouldShowLegend=true&sort=time&spanViewType=metadata&summary=qson%3A%28data%3A%21f%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Aratio%2CbreakdownAs%3Aabsolute&view=spans&start=1712867400000&end=1712871000000&paused=true)

We get significantly more 202s with lighthouse off

**Comment by Tonksthebear** [comment] 2024-04-16 17:02
Implemented the fix, waiting to hit prod and flip lighthouse back on

**Comment by Tonksthebear** [comment] 2024-04-17 23:51
I haven't seen any 404's today so I think we can close this. The fix seems to have done the trick

**Closed** 2024-04-17 23:53 UTC
Labels: API team
