### ISSUE TITLE
User feedback: App doesn't send notifications

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6597] opened 2023-08-28 13:36 UTC
From User:
"VA Health & Benefits app does not allow me to send push notifications to my phone.  
I'm using a Google Pixel 6 Pro. When I try to turn them on it tells me that this app doesn't send notifications. Screenshots attached."

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjlDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6f337c40f8e9084edfa94f44fb5adfb9a38a709d/Screenshot_20230823-183647.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0JDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d78cad91e756f3acac5765356f18f168796c0b01/Screenshot_20230823-183742.png)

**Comment by TKDickson** [comment] 2023-10-13 14:21
Dylan figured this one out!

> Looks like the user is at the notifications channels part of Android 13 instead of app settings/permissions. So looks like they went to the app > info menu > notifications instead of settings > Notifications > app settings > Scroll down till they see VA(will have a list of all their apps). [16 common Android notification problems and how to fix them](https://www.androidpolice.com/android-notification-problems-fixes/#check-notification-channels) 

This is one, FYI @timwright12 @bischoffa @jennb33 where we could help this veteran out if 1) Android allowed deeplinking into the relevant part of settings or 2) we could write back. As neither are an option, closing out this ticket as not a bug.

**Closed by TKDickson** 2023-10-13 14:21 UTC
Labels: bug, qa, user feedback
