### ISSUE TITLE
BUG - sev-3 - Android - Snackbar should never be null, but sometimes it is - add logging 

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5401] opened 2023-04-18 14:25 UTC
## What happened?

An interim fix was merged into the codebase to prevent crashes in Android when snackbars are null (ticket #4496), however snackBar shouldn't ever be null since it's a global variable.

Originally, we were keeping #4496 open to track the need to loop back around and figure out where snackbars are null/root cause, but since we've moved to a "one ticket, one PR" paradigm, opening a new ticket to track this instead.

## Specs:

- Device:
- OS: Android
- User Account:
- Accessibility State:

## Steps to Reproduce

We don't know the steps to reproduce, unfortunately -- can see the crash logs linked from the original ticket (#4496), and the first step of whichever Eng takes this would be to try to track down where they're coming from, and add that info to the ticket.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment] 2023-08-11 16:56
Planning just engineering work for this ticket for sprint work. No QA work expected.

**Comment by alexandec** [comment] 2023-08-21 23:06
I did some more research into this. My primary area of investigation was to find app states where `snackBar` could be null. I found that snackBar is assigned its value in App.tsx when the user is logged in:

```
<Toast {...snackBarProps} ref={(ref) => ((global.snackBar as ToastContainer | null) = ref)} offsetBottom={bottomOffset} />
```

So we're depending on the Toast component from [react-native-toast-notifications](https://github.com/arnnis/react-native-toast-notifications#readme) to assign a value to `snackBar` on login. Toast defines the type of `ref` as `Toast | null`, indicating that Toast might set snackBar to null. I looked quickly at Toast itself, and found that it initially sets the value of the ref to null, then places the toast object there. It's possible there are other circumstances where Toast may reset the ref to be null.

So I could imagine an issue if snackBar.hideAll() is called and:
- the user isn't logged in
- the user is logged in but Toast hasn't yet placed the ref in global.snackBar
- the user is logged in and Toast has modified global.snackBar to be null

I tried a few things to reproduce the error, but they all worked fine:
- Showing the snackbar, then logging out with the snackbar still visible. The snackbar disappears and I don't see an error.
- Visiting the location finder with snackbar still visible, then closing the snackbar. No errors.
- Showing the snackbar, killing the app, and reopening it. No errors.

If we were only making use of the snackbar inside react components, we could switch from the ref approach to the hook approach:

```
 const toast = useToast();
```

This could solve the problem, but since we show the snackbar from inside redux slices, I don't think we'll be able to use hooks in our case. 

Further investigation will be required to determine the exact app state where the problem occurs, and formulate a fix.

**Comment by alexandec** [comment] 2023-08-21 23:08
@bischoffa I wrote up my findings, increased the estimate, and move this back to the backlog.

**Comment by bischoffa** [comment] 2023-08-22 12:02
@alexandec thanks! Is there any tracking we could add in order to see when null happens and where for snackbars to help size/identify the issue?

**Comment by bischoffa** [comment] 2023-08-22 12:02
@alexandec thanks! Is there any tracking we could add in order to see when null happens and where for snackbars to help size/identify the issue?

**Comment by alexandec** [comment] 2023-08-22 14:12
@bischoffa Good idea, we could add a check in all seven locations we call `snackBar?.hideAll()`. If snackBar is null we could log a special analytics event.

**Comment by bischoffa** [comment] 2023-08-22 15:54
@alexandec can you size this ticket for that work?

**Comment by bischoffa** [comment] 2023-08-22 15:54
@jennb33 this is in the backlog as engineering has done their initial due diligence for this ticket. They spent 1 point to assess the problem. if not resolved they resize it and move it to the backlog so the work can be reprioritized for a future sprint.

**Comment by alexandec** [comment] 2023-08-22 17:57
@bischoffa sure, updated the estimate to cover adding and calling that event only.

**Comment by Sparowhawk** [comment] 2023-09-01 19:31
@rbontrager @alexandec Can you confirm this error is still happening. This ticket was created prior to update the library back in May for dependencies. So not sure if this is still happening.

**Comment by bischoffa** [comment] 2023-09-05 11:28
@rbontrager I did not have any QA points for bug tickets this sprint. I am okay with this waiting to be tested next sprint.

**Comment by alexandec** [comment] 2023-09-14 18:18
@Sparowhawk we'll have to add events to report when snackBar is null, to see if it's still happening. The change in #4496 prevents errors when snackBar is null so the user won't be inconvenienced (good) but it means we don't have any reporting to know if the issue remains. I'm working on adding that reporting in this ticket

**Comment by DJUltraTom** [comment] 2023-09-20 22:02
@alexandec Are there any QA steps that should be taken with this ticket? Or is this most recent code change to implement tracking around gaining more info on the bug?

**Comment by alexandec** [comment] 2023-09-20 22:24
@DJUltraTom Probably nothing for QA on this one. It's just adding an event that gets sent when snackBar is null. We don't know how to reproduce that condition so I don't think we can QA it

**Comment by alexandec** [comment] 2023-09-21 14:19
@bischoffa this ticket is unusual because:
- There's nothing to QA
- There's a PR to merge, but the PR won't resolve the bug. It only adds analytics to determine whether the issue is still happening
- We'll need to wait multiple weeks until the code is in production on people's phones and we have enough analytics data to determine whether the issue is still happening

What do you recommend we do with this ticket?

**Comment by bischoffa** [comment] 2023-09-21 14:29
@alexandec lets move forward with getting the analytics out to learn more. I will create a subsequent ticket to follow-up post prod launch which I think is 10/10 for work done in this sprint.

**Comment by bischoffa** [comment] 2023-09-21 14:32
Reviewing logging ticket is #6789

**Comment by alexandec** [comment] 2023-09-21 20:59
@bischoffa sounds good, thanks for creating that followup ticket. I merged the PR to add the analytics, so I'll close this ticket.

**Closed by alexandec** 2023-09-21 20:59 UTC
Labels: sev-3, bug, front-end, mobile-blue-team, scrubbed
